import { createHash, randomUUID } from "node:crypto";
import { mkdir, stat } from "node:fs/promises";
import { join } from "node:path";
import { absolutePath, changeDescription, changeId, isolatedWorkspaceWriteLease, jjOperationId, workspaceId, workspaceName, workspaceWriteLeaseId, type ChangeDescription, type IsolatedWorkspaceWriteLease, type SourceWorkspaceHandle, type WorkspaceId, type WorkspaceRebaseLease } from "./domain.ts";
import { type JjExecutor, renderJjExecutionFailure } from "./executor.ts";
import type { CreateWorkspaceReceipt, JjOperationResult, WorkspaceCheckpointReceipt, WorkspaceRebaseReceipt, WorkspaceRebaseTarget, WorkspaceReportReceipt } from "./operations.ts";
import type { JjRepositoryKernel } from "./repository.ts";
import { exactChange } from "./repository.ts";
import { updateStaleSafely } from "./stale-update.ts";
import { MAX_INLINE_WORKSPACE_EVIDENCE_BYTES, type WorkspaceArtifactStore } from "./workspace-artifacts.ts";
import { JjWorkspaceRepositoryKernel } from "./workspace-repository.ts";
import type { IsolatedWorkspaceStore, PersistedIsolatedWorkspaceV1, PersistedWorkspaceIdentityV1, PersistedWorkspaceOperationV1 } from "./workspace-persistence.ts";

const ID_TEMPLATE = 'change_id ++ "\\n"';
export class IsolatedJjOperations {
  private readonly options: { sources: JjRepositoryKernel; workspaces: IsolatedWorkspaceStore; repository: JjWorkspaceRepositoryKernel; executor: JjExecutor; artifacts?: WorkspaceArtifactStore; now?: () => string; failpoint?: (operation: string, boundary: string) => void };
  constructor(options: { sources: JjRepositoryKernel; workspaces: IsolatedWorkspaceStore; repository: JjWorkspaceRepositoryKernel; executor: JjExecutor; artifacts?: WorkspaceArtifactStore; now?: () => string; failpoint?: (operation: string, boundary: string) => void }) { this.options = options; }
  private now(): string { return (this.options.now ?? (() => new Date().toISOString()))(); }

  async createWorkspace(source: SourceWorkspaceHandle, input: { name: ReturnType<typeof workspaceName>; ownerContextId: string; rootSessionId: string }): Promise<JjOperationResult<CreateWorkspaceReceipt & { lease: IsolatedWorkspaceWriteLease; path: string }>> {
    return this.options.sources.withRepositoryMutation(source, async () => {
      const inspected = await this.options.sources.inspect(source);
      if (!inspected.source.wip || inspected.source.wip.changeId !== inspected.current.changeId) return { kind: "blocked", blocker: { kind: "decision_required", reason: "Source @ is not the tracked WIP change." } };
      if (inspected.current.parentChangeIds.length !== 1) return { kind: "blocked", blocker: { kind: "foreign_work", reason: "Source WIP must have exactly one parent before workspace allocation." } };
      const id = workspaceId(`workspace-${randomUUID()}`); const allocationId = `allocation-${randomUUID()}`; const operationId = `jjop-${randomUUID()}`; const at = this.now();
      const path = join(inspected.source.workspacePath, ".jj", "workspaces", input.name);
      const patch = await this.options.sources.patchEvidence(source, exactChange(inspected.current.changeId)); const sourcePatchHash = sha(patch);
      const allocating: PersistedIsolatedWorkspaceV1 = { version: 1, phase: "allocating", workspaceId: id, allocation: { allocationId, operationId, rootSessionId: input.rootSessionId, ownerContextId: input.ownerContextId, sourceId: source.sourceId, sourceWipChangeId: inspected.current.changeId, baseChangeId: inspected.current.parentChangeIds[0]!, sourcePatchHash, name: input.name, path, startedAt: at, beforeJjOperationId: inspected.jjOperationId }, createdAt: at, updatedAt: at };
      await this.options.workspaces.create(allocating); await mkdir(join(inspected.source.workspacePath, ".jj", "workspaces"), { recursive: true, mode: 0o700 });
      try {
        await this.options.sources.runMutation(source, ["workspace", "add", path, "--name", input.name, "--revision", exactChange(inspected.current.parentChangeIds[0]!)]); this.options.failpoint?.("allocate_workspace", "after_mutation");
        const [root, sourceAfter, patchAfter] = await Promise.all([this.readId(path, "@"), this.options.sources.currentChangeId(source), this.options.sources.patchEvidence(source, exactChange(inspected.current.changeId))]);
        if (sourceAfter !== inspected.current.changeId || sha(patchAfter) !== sourcePatchHash) throw new Error("Source WIP identity or content changed during workspace allocation.");
        const parent = await this.readId(path, "@-"); if (parent !== inspected.current.parentChangeIds[0]) throw new Error("Allocated workspace root has an unexpected parent.");
        const afterJjOperationId = await this.readOperationId(path); const leaseId = workspaceWriteLeaseId(`lease-${randomUUID()}`); const identity: PersistedWorkspaceIdentityV1 = { workspaceId: id, rootSessionId: input.rootSessionId, sourceId: source.sourceId, sourceWipChangeId: inspected.current.changeId, baseChangeId: parent, name: input.name, path, rootChangeId: root, expectedHeadChangeId: root };
        const receipt = { workspaceId: id, name: input.name, rootChangeId: root, workspaceHeadChangeId: root, sourceWipChangeId: inspected.current.changeId, operationId: jjOperationId(operationId) };
        await this.options.workspaces.update(id, (record) => ({ version: 1, phase: "active", identity, writer: { phase: "leased", ownerContextId: input.ownerContextId, leaseId, headChangeId: root, generation: 1, acquiredAt: at }, targets: [], claims: [], operations: [{ operationId, kind: "allocate_workspace", idempotencyKey: allocationId, startedAt: at, beforeJjOperationId: inspected.jjOperationId, intent: { allocationId, sourceWipChangeId: inspected.current.changeId, baseChangeId: parent, name: input.name, path }, outcome: { phase: "completed", completedAt: this.now(), afterJjOperationId, receipt } }], createdAt: record.createdAt, updatedAt: this.now() }));
        return { kind: "completed", receipt: { ...receipt, lease: isolatedWorkspaceWriteLease(id, leaseId), path } };
      } catch (error) { await this.options.workspaces.update(id, (record) => ({ version: 1, phase: "incident", workspaceId: id, lastSafePhase: "allocating", reason: error instanceof Error ? error.message : String(error), evidence: record, stoppedAt: this.now(), createdAt: record.createdAt, updatedAt: this.now() })); throw error; }
    });
  }

  async checkpointWorkspace(lease: IsolatedWorkspaceWriteLease, input: { description: ChangeDescription }): Promise<JjOperationResult<WorkspaceCheckpointReceipt & { lease: IsolatedWorkspaceWriteLease }>> {
    const record = await this.requireActive(lease.workspaceId); const writer = record.writer;
    if (writer.phase !== "leased" || writer.leaseId !== lease.leaseId) return { kind: "blocked", blocker: { kind: "foreign_work", reason: "Workspace write lease is stale or inactive." } };
    const operationId = `jjop-${randomUUID()}`; const at = this.now(); const before = await this.options.repository.currentOperationId(record.identity);
    await this.options.workspaces.update(lease.workspaceId, (current) => { if (current.phase !== "active" || current.writer.phase !== "leased" || current.writer.leaseId !== lease.leaseId) throw new Error("Workspace lease changed before checkpoint."); return { ...current, writer: { phase: "checkpointing", ownerContextId: writer.ownerContextId, leaseId: writer.leaseId, expectedHeadChangeId: writer.headChangeId, generation: writer.generation, operationId, startedAt: at }, operations: [...current.operations, startedOperation(operationId, "workspace_checkpoint", `checkpoint:${writer.leaseId}`, at, before, { expectedHeadChangeId: writer.headChangeId, description: input.description, ownerContextId: writer.ownerContextId, leaseId: writer.leaseId, generation: writer.generation })], updatedAt: at }; });
    try {
      return await this.options.repository.mutate(lease.workspaceId, async (identity) => {
        const inspected = await this.options.repository.inspect(lease.workspaceId); if (inspected.head.changeId !== writer.headChangeId) throw new Error("Workspace head changed without a checkpoint receipt.");
        await this.setBoundary(lease.workspaceId, operationId, "mutating");
        await this.options.repository.run(identity, ["describe", "--message", input.description]); this.options.failpoint?.("workspace_checkpoint", "after_describe"); await this.options.repository.run(identity, ["new"]); this.options.failpoint?.("workspace_checkpoint", "after_new"); await this.setBoundary(lease.workspaceId, operationId, "verifying"); const next = await this.readId(identity.path, "@"); const nextParent = await this.readId(identity.path, "@-"); if (nextParent !== writer.headChangeId || next === writer.headChangeId) throw new Error("Checkpoint did not create exactly one child head.");
        const after = await this.options.repository.currentOperationId(identity); const nextLeaseId = workspaceWriteLeaseId(`lease-${randomUUID()}`); const receipt: WorkspaceCheckpointReceipt = { workspaceId: lease.workspaceId, checkpointedChangeId: changeId(writer.headChangeId), previousHeadChangeId: changeId(writer.headChangeId), newHeadChangeId: next, description: changeDescription(input.description), parentChangeIds: [changeId(writer.headChangeId)], conflicted: inspected.head.conflicted, operationId: jjOperationId(operationId) };
        await this.options.workspaces.update(lease.workspaceId, (current) => { if (current.phase !== "active") throw new Error("Workspace left active phase during checkpoint."); return { ...current, identity: { ...current.identity, expectedHeadChangeId: next }, writer: { phase: "leased", ownerContextId: writer.ownerContextId, leaseId: nextLeaseId, headChangeId: next, generation: writer.generation + 1, acquiredAt: this.now() }, operations: completeOperation(current.operations, operationId, after, receipt, this.now()), updatedAt: this.now() }; });
        return { kind: "completed", receipt: { ...receipt, lease: isolatedWorkspaceWriteLease(lease.workspaceId, nextLeaseId) } };
      });
    } catch (error) { await this.markUnknown(lease.workspaceId, operationId, error); return { kind: "blocked", blocker: { kind: "unknown_partial_mutation", operationId: jjOperationId(operationId), phase: "workspace_checkpoint" } }; }
  }

  async releaseWriter(lease: IsolatedWorkspaceWriteLease): Promise<void> { await this.options.workspaces.update(lease.workspaceId, (record) => { if (record.phase !== "active" || record.writer.phase !== "leased" || record.writer.leaseId !== lease.leaseId) throw new Error("Cannot release a stale workspace lease."); return { ...record, writer: { phase: "available", headChangeId: record.writer.headChangeId, generation: record.writer.generation }, updatedAt: this.now() }; }); }

  async acquireWriter(id: WorkspaceId, ownerContextId: string): Promise<IsolatedWorkspaceWriteLease> {
    const leaseId = workspaceWriteLeaseId(`lease-${randomUUID()}`);
    await this.options.workspaces.update(id, (record) => { if (record.phase !== "active" || record.writer.phase !== "available") throw new Error("Workspace writer is not available."); return { ...record, writer: { phase: "leased", ownerContextId, leaseId, headChangeId: record.writer.headChangeId, generation: record.writer.generation + 1, acquiredAt: this.now() }, updatedAt: this.now() }; });
    return isolatedWorkspaceWriteLease(id, leaseId);
  }

  async transferWriter(lease: IsolatedWorkspaceWriteLease, ownerContextId: string): Promise<IsolatedWorkspaceWriteLease> {
    const nextLeaseId = workspaceWriteLeaseId(`lease-${randomUUID()}`);
    await this.options.workspaces.update(lease.workspaceId, (record) => { if (record.phase !== "active" || record.writer.phase !== "leased" || record.writer.leaseId !== lease.leaseId) throw new Error("Cannot transfer a stale workspace lease."); return { ...record, writer: { phase: "leased", ownerContextId, leaseId: nextLeaseId, headChangeId: record.writer.headChangeId, generation: record.writer.generation + 1, acquiredAt: this.now() }, updatedAt: this.now() }; });
    return isolatedWorkspaceWriteLease(lease.workspaceId, nextLeaseId);
  }

  async rebaseWorkspace(lease: WorkspaceRebaseLease, target: WorkspaceRebaseTarget): Promise<JjOperationResult<WorkspaceRebaseReceipt>> {
    const record = await this.requireActive(lease.workspaceId); if (record.writer.phase !== "available" || unsettledClaims(record).length) return { kind: "blocked", blocker: { kind: "foreign_work", reason: "Workspace rebase requires no live writer or unsettled file claim." } };
    const operationId = `jjop-${randomUUID()}`; const before = await this.options.repository.currentOperationId(record.identity); const at = this.now();
    const entries = await this.options.repository.range(lease.workspaceId, changeId(record.identity.rootChangeId), changeId(record.identity.expectedHeadChangeId)); const content = [...entries].reverse().find((entry) => !entry.empty); const beforeHash = await this.options.repository.patchHash(lease.workspaceId, `${exactChange(changeId(record.identity.rootChangeId))}::${exactChange(changeId(content?.changeId ?? record.identity.rootChangeId))}`);
    const source = await this.options.sources.inspect({ kind: "source_workspace", sourceId: record.identity.sourceId } as SourceWorkspaceHandle); const targetId = target.kind === "source_parent" ? source.current.parentChangeIds[0] : target.changeId; if (!targetId) return { kind: "blocked", blocker: { kind: "decision_required", reason: "Unable to resolve rebase target." } };
    await this.options.workspaces.update(lease.workspaceId, (current) => current.phase === "active" ? { ...current, writer: { phase: "rebasing", ownerContextId: record.identity.rootSessionId, expectedHeadChangeId: record.identity.expectedHeadChangeId, generation: record.writer.generation, operationId, startedAt: at }, operations: [...current.operations, startedOperation(operationId, "rebase_workspace", `rebase:${targetId}`, at, before, { rootChangeId: record.identity.rootChangeId, expectedHeadChangeId: record.identity.expectedHeadChangeId, oldBaseChangeId: record.identity.baseChangeId, targetChangeId: targetId, orderedChangeIds: entries.map((entry) => entry.changeId), beforePatchHash: beforeHash })], updatedAt: at } : current);
    try { return await this.options.repository.mutate(lease.workspaceId, async (identity) => {
      await this.setBoundary(lease.workspaceId, operationId, "mutating");
      await this.options.repository.run(identity, ["--ignore-working-copy", "rebase", "--source", exactChange(changeId(identity.rootChangeId)), "--destination", exactChange(targetId)]); await updateStaleSafely({ context: "Workspace rebase", location: identity.path, read: (args) => this.options.repository.readOnly(identity, args), run: (args) => this.options.repository.run(identity, args) }); this.options.failpoint?.("rebase_workspace", "after_mutation"); await this.setBoundary(lease.workspaceId, operationId, "verifying");
      const afterEntries = await this.options.repository.range(lease.workspaceId, changeId(identity.rootChangeId), changeId(identity.expectedHeadChangeId)); if (afterEntries.map((item) => item.changeId).join() !== entries.map((item) => item.changeId).join()) throw new Error("Workspace range identity or order changed during rebase.");
      const afterHash = await this.options.repository.patchHash(lease.workspaceId, `${exactChange(changeId(identity.rootChangeId))}::${exactChange(changeId(content?.changeId ?? identity.rootChangeId))}`); const conflicts = (await Promise.all(afterEntries.map((entry) => this.options.repository.conflicts(lease.workspaceId, exactChange(entry.changeId))))).flat(); const after = await this.options.repository.currentOperationId(identity);
      const base = await this.readId(identity.path, `parents(${exactChange(changeId(identity.rootChangeId))})`); const common = { workspaceId: lease.workspaceId, rootChangeId: changeId(identity.rootChangeId), contentTipChangeId: changeId(content?.changeId ?? identity.rootChangeId), workspaceHeadChangeId: changeId(identity.expectedHeadChangeId), oldBaseChangeId: changeId(identity.baseChangeId), newBaseChangeId: base, operationId: jjOperationId(operationId) };
      const receipt: WorkspaceRebaseReceipt = conflicts.length ? { ...common, disposition: "conflicted", conflictPaths: [...new Set(conflicts)].sort() } : beforeHash === afterHash ? { ...common, disposition: "range_equivalent", normalizedPatchHash: afterHash } : { ...common, disposition: "range_changed", beforePatchHash: beforeHash, afterPatchHash: afterHash };
      await this.options.workspaces.update(lease.workspaceId, (current) => { if (current.phase !== "active") throw new Error(); return { ...current, identity: { ...current.identity, baseChangeId: base }, writer: { phase: "available", headChangeId: current.identity.expectedHeadChangeId, generation: record.writer.generation + 1 }, operations: completeOperation(current.operations, operationId, after, receipt, this.now()), updatedAt: this.now() }; }); return { kind: "completed", receipt };
    }); } catch (error) { await this.markUnknown(lease.workspaceId, operationId, error); return { kind: "blocked", blocker: { kind: "unknown_partial_mutation", operationId: jjOperationId(operationId), phase: "rebase_workspace" } }; }
  }

  async reconstructWorkspaceAttachment(id: WorkspaceId): Promise<{ workspaceId: WorkspaceId; path: string; headChangeId: string; reconstructed: boolean; operationId: string }> {
    const record = await this.options.workspaces.get(id); if (!record || !("identity" in record) || !record.identity) throw new Error("Workspace custody has no reconstructable identity."); const identity = record.identity; const source = { kind: "source_workspace", sourceId: identity.sourceId } as SourceWorkspaceHandle;
    return this.options.sources.withRepositoryMutation(source, async () => {
      let attachmentExists = true; try { await stat(identity.path); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") attachmentExists = false; else throw error; }
      if (attachmentExists) { const observed = await this.readId(identity.path, "@"); if (observed !== identity.expectedHeadChangeId) throw new Error("Existing workspace attachment points at an unexpected head."); return { workspaceId: id, path: identity.path, headChangeId: observed, reconstructed: false, operationId: await this.readOperationId(identity.path) }; }
      const temporaryName = workspaceName(`${identity.name.slice(0, 32)}-recovery-${randomUUID().slice(0, 6)}`);
      await mkdir(identity.path, { recursive: true, mode: 0o700 });
      await this.options.sources.runMutation(source, ["workspace", "add", identity.path, "--name", temporaryName, "--revision", exactChange(changeId(identity.expectedHeadChangeId))]);
      try { await this.options.sources.runMutation(source, ["workspace", "forget", identity.name]); } catch (error) { if (!String(error).match(/0 workspace|No workspace|not found/i)) throw error; }
      await this.options.repository.run(identity, ["workspace", "rename", identity.name]);
      const observed = await this.readId(identity.path, "@");
      if (observed !== identity.expectedHeadChangeId) { const replacement = await this.options.repository.resolveRevision(id, exactChange(observed)); if (!replacement.empty || replacement.parentChangeIds.length !== 1 || replacement.parentChangeIds[0] !== identity.expectedHeadChangeId) throw new Error("Reconstructed workspace attachment has an unexpected head."); }
      const operationId = await this.readOperationId(identity.path);
      await this.options.workspaces.update(id, (current) => { if (!("identity" in current) || !current.identity) return current; const priorHead = current.identity.expectedHeadChangeId; return { ...current, identity: { ...current.identity, expectedHeadChangeId: observed }, ...(current.phase === "active" ? { writer: { phase: "available" as const, headChangeId: observed, generation: current.writer.generation + 1 }, targets: current.targets.map((target) => target.wipChangeId === priorHead ? { ...target, wipChangeId: observed } : target), claims: current.claims.map((claim) => claim.wipChangeId === priorHead ? { ...claim, wipChangeId: observed } : claim) } : {}), ...(current.phase === "incident" ? { evidence: { prior: current.evidence, attachmentReconstruction: { path: identity.path, priorHeadChangeId: priorHead, headChangeId: observed, operationId } } } : {}), updatedAt: this.now() }; });
      return { workspaceId: id, path: identity.path, headChangeId: observed, reconstructed: true, operationId };
    });
  }

  async reconcileAllocation(id: WorkspaceId): Promise<"nothing" | "completed" | "safe_to_resume" | "attention_required"> {
    const record = await this.options.workspaces.get(id); if (!record || record.phase !== "incident" || record.lastSafePhase !== "allocating") return "nothing";
    try {
      const evidence = asRecord(record.evidence); if (evidence.phase !== "allocating") return "attention_required"; const allocation = asRecord(evidence.allocation);
      const sourceId = requiredString(allocation.sourceId, "allocation source"); const source = await this.options.sources.inspect({ kind: "source_workspace", sourceId } as SourceWorkspaceHandle); const expectedWip = changeId(requiredString(allocation.sourceWipChangeId, "source WIP"));
      if (source.current.changeId !== expectedWip || sha(await this.options.sources.patchEvidence({ kind: "source_workspace", sourceId } as SourceWorkspaceHandle, exactChange(expectedWip))) !== requiredString(allocation.sourcePatchHash, "source patch hash")) return "attention_required";
      const path = requiredString(allocation.path, "workspace path"); let root: ReturnType<typeof changeId>;
      try { root = await this.readId(path, "@"); } catch { return source.jjOperationId === requiredString(allocation.beforeJjOperationId, "before operation") ? "safe_to_resume" : "attention_required"; }
      const base = await this.readId(path, "@-"); if (base !== requiredString(allocation.baseChangeId, "allocation base")) return "attention_required";
      const identity: PersistedWorkspaceIdentityV1 = { workspaceId: id, rootSessionId: requiredString(allocation.rootSessionId, "root session"), sourceId, sourceWipChangeId: expectedWip, baseChangeId: base, name: requiredString(allocation.name, "workspace name"), path, rootChangeId: root, expectedHeadChangeId: root };
      const operationId = requiredString(allocation.operationId, "allocation operation"); const receipt = { workspaceId: id, name: workspaceName(identity.name), rootChangeId: root, workspaceHeadChangeId: root, sourceWipChangeId: expectedWip, operationId: jjOperationId(operationId) }; const after = await this.readOperationId(path);
      await this.options.workspaces.update(id, (current) => ({ version: 1, phase: "active", identity, writer: { phase: "available", headChangeId: root, generation: 0 }, targets: [], claims: [], operations: [{ operationId, kind: "allocate_workspace", idempotencyKey: requiredString(allocation.allocationId, "allocation ID"), startedAt: requiredString(allocation.startedAt, "allocation start"), beforeJjOperationId: requiredString(allocation.beforeJjOperationId, "before operation"), intent: allocation, outcome: { phase: "completed", completedAt: this.now(), afterJjOperationId: after, receipt } }], createdAt: current.createdAt, updatedAt: this.now() })); return "completed";
    } catch { return "attention_required"; }
  }

  async reconcileInterrupted(id: WorkspaceId): Promise<"nothing" | "completed" | "safe_to_resume" | "attention_required"> {
    const record = await this.options.workspaces.get(id); if (!record || record.phase !== "active" || record.writer.phase !== "interrupted") return "nothing";
    const operation = [...record.operations].reverse().find((item) => item.outcome.phase === "started" || item.outcome.phase === "unknown");
    if (!operation) return "safe_to_resume";
    const intent = asRecord(operation.intent);
    try {
      if (operation.kind === "workspace_checkpoint") {
        const expected = changeId(requiredString(intent.expectedHeadChangeId, "checkpoint expected head")); const description = requiredString(intent.description, "checkpoint description"); const inspection = await this.options.repository.inspect(id);
        if (inspection.head.changeId === expected) {
          const old = await this.options.repository.resolveTracked(id, expected);
          return old.description === description ? "safe_to_resume" : operation.outcome.phase === "started" && operation.outcome.boundary === "prepared" && inspection.operationId === operation.beforeJjOperationId ? "safe_to_resume" : "attention_required";
        }
        const old = await this.options.repository.resolveTracked(id, expected);
        if (!inspection.head.empty || inspection.head.parentChangeIds.length !== 1 || inspection.head.parentChangeIds[0] !== expected || old.description !== description) return "attention_required";
        const receipt: WorkspaceCheckpointReceipt = { workspaceId: id, checkpointedChangeId: expected, previousHeadChangeId: expected, newHeadChangeId: inspection.head.changeId, description: changeDescription(description), parentChangeIds: [expected], conflicted: old.conflicted, operationId: jjOperationId(operation.operationId) };
        await this.options.workspaces.update(id, (current) => { if (current.phase !== "active") return current; return { ...current, identity: { ...current.identity, expectedHeadChangeId: inspection.head.changeId }, writer: { phase: "available", headChangeId: inspection.head.changeId, generation: current.writer.generation + 1 }, operations: completeOperation(current.operations, operation.operationId, inspection.operationId, receipt, this.now()), updatedAt: this.now() }; }); return "completed";
      }
      if (operation.kind === "rebase_workspace") {
        const root = changeId(requiredString(intent.rootChangeId, "rebase root")); const head = changeId(requiredString(intent.expectedHeadChangeId, "rebase head")); const target = changeId(requiredString(intent.targetChangeId, "rebase target")); const ordered = requiredStrings(intent.orderedChangeIds, "rebase ordered IDs");
        const entries = await this.options.repository.range(id, root, head); if (entries.map((entry) => entry.changeId).join() !== ordered.join()) return "attention_required";
        const rootState = await this.options.repository.resolveTracked(id, root); if (rootState.parentChangeIds.length !== 1) return "attention_required";
        if (rootState.parentChangeIds[0] !== target) return operation.outcome.phase === "started" && operation.outcome.boundary === "prepared" ? "safe_to_resume" : "attention_required";
        const content = [...entries].reverse().find((entry) => !entry.empty); const afterHash = await this.options.repository.patchHash(id, `${exactChange(root)}::${exactChange(content?.changeId ?? root)}`); const conflicts = (await Promise.all(entries.map((entry) => this.options.repository.conflicts(id, exactChange(entry.changeId))))).flat(); const beforeHash = requiredString(intent.beforePatchHash, "rebase patch hash");
        const common = { workspaceId: id, rootChangeId: root, contentTipChangeId: content?.changeId ?? root, workspaceHeadChangeId: head, oldBaseChangeId: changeId(requiredString(intent.oldBaseChangeId, "old base")), newBaseChangeId: target, operationId: jjOperationId(operation.operationId) };
        const receipt: WorkspaceRebaseReceipt = conflicts.length ? { ...common, disposition: "conflicted", conflictPaths: [...new Set(conflicts)].sort() } : beforeHash === afterHash ? { ...common, disposition: "range_equivalent", normalizedPatchHash: afterHash } : { ...common, disposition: "range_changed", beforePatchHash: beforeHash, afterPatchHash: afterHash };
        const afterOperationId = (await this.options.repository.inspect(id)).operationId; await this.options.workspaces.update(id, (current) => { if (current.phase !== "active") return current; return { ...current, identity: { ...current.identity, baseChangeId: target }, writer: { phase: "available", headChangeId: head, generation: current.writer.generation + 1 }, operations: completeOperation(current.operations, operation.operationId, afterOperationId, receipt, this.now()), updatedAt: this.now() }; }); return "completed";
      }
      if (operation.kind === "normalize_change_range") {
        const descriptions = Array.isArray(intent.descriptions) ? intent.descriptions.map(asRecord) : []; const emptyIds = requiredStrings(intent.emptyChangeIds, "normalization empty IDs");
        for (const description of descriptions) { const state = await this.options.repository.resolveTracked(id, changeId(requiredString(description.changeId, "description change ID"))); if (state.description !== requiredString(description.description, "description")) return "safe_to_resume"; }
        for (const empty of emptyIds) { try { await this.options.repository.resolveTracked(id, changeId(empty)); return "safe_to_resume"; } catch { /* exact absence proves this step complete */ } }
        const inspection = await this.options.repository.inspect(id); const receipt = { removedEmptyChangeIds: emptyIds, describedChangeIds: descriptions.map((item) => requiredString(item.changeId, "description change ID")), operationId: operation.operationId }; await this.options.workspaces.update(id, (current) => current.phase !== "active" ? current : { ...current, writer: { phase: "available", headChangeId: current.identity.expectedHeadChangeId, generation: current.writer.generation + 1 }, operations: completeOperation(current.operations, operation.operationId, inspection.operationId, receipt, this.now()), updatedAt: this.now() }); return "completed";
      }
      return "attention_required";
    } catch { return "attention_required"; }
  }

  async normalizeChangeRange(id: WorkspaceId, descriptions: readonly { changeId: string; description: ChangeDescription }[]): Promise<JjOperationResult<{ removedEmptyChangeIds: readonly string[]; describedChangeIds: readonly string[]; operationId: string }>> {
    const record = await this.requireActive(id); if (record.writer.phase !== "available" || unsettledClaims(record).length) return { kind: "blocked", blocker: { kind: "foreign_work", reason: "Workspace normalization requires no live writer or unsettled file claim." } };
    const operationId = `jjop-${randomUUID()}`; const at = this.now(); const before = await this.options.repository.currentOperationId(record.identity);
    const entries = await this.options.repository.range(id, changeId(record.identity.rootChangeId), changeId(record.identity.expectedHeadChangeId));
    const interiorEmpty = entries.filter((entry) => entry.empty && entry.changeId !== record.identity.rootChangeId && entry.changeId !== record.identity.expectedHeadChangeId).map((entry) => entry.changeId);
    const allowed = new Set(entries.filter((entry) => !entry.empty && entry.changeId !== record.identity.expectedHeadChangeId).map((entry) => entry.changeId));
    for (const item of descriptions) if (!allowed.has(item.changeId as any)) return { kind: "blocked", blocker: { kind: "foreign_work", reason: `Description target ${item.changeId} is outside the owned nonempty range.` } };
    await this.options.workspaces.update(id, (current) => current.phase === "active" ? { ...current, operations: [...current.operations, startedOperation(operationId, "normalize_change_range", `normalize:${current.identity.expectedHeadChangeId}`, at, before, { rootChangeId: record.identity.rootChangeId, expectedHeadChangeId: record.identity.expectedHeadChangeId, descriptions, emptyChangeIds: interiorEmpty })], updatedAt: at } : current);
    try { return await this.options.repository.mutate(id, async (identity) => {
      await this.setBoundary(id, operationId, "mutating");
      for (const item of descriptions) await this.options.repository.run(identity, ["--ignore-working-copy", "describe", "--message", item.description, exactChange(changeId(item.changeId))]);
      for (const empty of interiorEmpty) await this.options.repository.run(identity, ["--ignore-working-copy", "abandon", exactChange(empty)]);
      this.options.failpoint?.("normalize_change_range", "after_mutation");
      await this.setBoundary(id, operationId, "verifying");
      const afterInspection = await this.options.repository.inspect(id); if (afterInspection.head.changeId !== record.identity.expectedHeadChangeId) throw new Error("Normalization changed tracked workspace head identity.");
      const after = await this.options.repository.currentOperationId(identity); const receipt = { removedEmptyChangeIds: interiorEmpty, describedChangeIds: descriptions.map((item) => item.changeId), operationId };
      await this.options.workspaces.update(id, (current) => { if (current.phase !== "active") throw new Error(); return { ...current, operations: completeOperation(current.operations, operationId, after, receipt, this.now()), updatedAt: this.now() }; }); return { kind: "completed", receipt };
    }); } catch (error) { await this.markUnknown(id, operationId, error); return { kind: "blocked", blocker: { kind: "unknown_partial_mutation", operationId: jjOperationId(operationId), phase: "normalize_change_range" } }; }
  }

  async prepareWorkspaceReport(id: WorkspaceId): Promise<JjOperationResult<WorkspaceReportReceipt>> {
    const record = await this.requireActive(id); if (record.writer.phase !== "available" || unsettledClaims(record).length) return { kind: "blocked", blocker: { kind: "foreign_work", reason: "Workspace report requires no live writer or unsettled file claim." } };
    const inspected = await this.options.repository.inspect(id); if (inspected.head.changeId !== record.identity.expectedHeadChangeId || !inspected.head.empty) return { kind: "blocked", blocker: { kind: "identity_mismatch", expected: changeId(record.identity.expectedHeadChangeId), observed: [inspected.head.changeId] } };
    const foreign = await this.options.repository.foreignDescendants(id, changeId(record.identity.rootChangeId), changeId(record.identity.expectedHeadChangeId)); if (foreign.length) return { kind: "blocked", blocker: { kind: "foreign_work", reason: `Workspace has ${foreign.length} foreign descendant(s).` } };
    const entries = await this.options.repository.range(id, changeId(record.identity.rootChangeId), changeId(record.identity.expectedHeadChangeId)); const reviewEntries = entries.filter((entry) => entry.changeId !== inspected.head.changeId); const unnamed = reviewEntries.filter((entry) => !entry.empty && !entry.description.trim()); if (unnamed.length) return { kind: "blocked", blocker: { kind: "decision_required", reason: "Every retained nonempty change must be named." } };
    const content = [...reviewEntries].reverse().find((entry) => !entry.empty); const operationId = `jjop-${randomUUID()}`; const ordered = reviewEntries.map((entry) => entry.changeId); const receipt: WorkspaceReportReceipt = content ? { workspaceId: id, rootChangeId: changeId(record.identity.rootChangeId), workspaceHeadChangeId: inspected.head.changeId, contentTipChangeId: content.changeId, range: "nonempty", operationId: jjOperationId(operationId) } : { workspaceId: id, rootChangeId: changeId(record.identity.rootChangeId), workspaceHeadChangeId: inspected.head.changeId, range: "empty", operationId: jjOperationId(operationId) };
    const conflictPaths = [...new Set((await Promise.all(reviewEntries.map((entry) => this.options.repository.conflicts(id, exactChange(entry.changeId))))).flat())].sort();
    const fullEvidence = { orderedChangeIds: ordered, conflictPaths, changes: reviewEntries.map((entry) => ({ changeId: entry.changeId, description: entry.description, empty: entry.empty, conflicted: entry.conflicted, changedPaths: entry.changedPaths })) };
    const evidenceBytes = Buffer.byteLength(JSON.stringify(fullEvidence), "utf8");
    const evidence = evidenceBytes <= MAX_INLINE_WORKSPACE_EVIDENCE_BYTES ? { evidence: "inline" as const, orderedChangeIds: ordered, conflictPaths } : this.options.artifacts ? { evidence: "artifact" as const, artifact: await this.options.artifacts.putJson(id, "workspace-range", fullEvidence), changeCount: ordered.length, conflictCount: conflictPaths.length } : (() => { throw new Error("Workspace range evidence exceeds the inline limit and no artifact store is configured."); })();
    const report = content ? { range: "nonempty" as const, contentTipChangeId: content.changeId, normalizedPatchHash: await this.options.repository.patchHash(id, `${exactChange(changeId(record.identity.rootChangeId))}::${exactChange(content.changeId)}`), ...evidence } : { range: "empty" as const, proofHash: sha(JSON.stringify(fullEvidence)), ...evidence };
    const before = await this.options.repository.currentOperationId(record.identity); const operation: PersistedWorkspaceOperationV1 = { ...startedOperation(operationId, "prepare_workspace_report", `report:${record.identity.expectedHeadChangeId}`, this.now(), before, { rootChangeId: record.identity.rootChangeId, expectedHeadChangeId: record.identity.expectedHeadChangeId }), outcome: { phase: "completed", completedAt: this.now(), afterJjOperationId: before, receipt } };
    await this.options.workspaces.update(id, (current) => { if (current.phase !== "active") throw new Error(); return { version: 1, phase: "reported", identity: current.identity, reportOperationId: operationId, reportVersion: (current.reviewCycle ?? 0) + 1, ...(current.reviewCycle !== undefined ? { reviewCycle: current.reviewCycle } : {}), ...(current.priorReviewIds ? { priorReviewIds: current.priorReviewIds } : {}), report, operations: [...current.operations, operation], createdAt: current.createdAt, updatedAt: this.now() }; }); return { kind: "completed", receipt };
  }

  private async setBoundary(id: WorkspaceId, operationId: string, boundary: "prepared" | "mutating" | "verifying"): Promise<void> { await this.options.workspaces.update(id, (record) => record.phase !== "active" ? record : { ...record, operations: record.operations.map((item) => item.operationId === operationId && item.outcome.phase === "started" ? { ...item, outcome: { phase: "started", boundary } } : item), updatedAt: this.now() }); }
  private async requireActive(id: WorkspaceId) { const record = await this.options.workspaces.get(id); if (!record || record.phase !== "active") throw new Error(`Workspace ${id} is not active.`); return record; }
  private async markUnknown(id: WorkspaceId, operationId: string, error: unknown): Promise<void> { await this.options.workspaces.update(id, (record) => { if (record.phase !== "active") return record; const reason = error instanceof Error ? error.message : String(error); const writer = record.writer; const owner = writer.phase === "available" ? record.identity.rootSessionId : writer.phase === "interrupted" ? writer.priorOwnerContextId : writer.ownerContextId; return { ...record, writer: { phase: "interrupted", priorPhase: writer.phase === "available" || writer.phase === "interrupted" ? "checkpointing" : writer.phase, priorOwnerContextId: owner, expectedHeadChangeId: record.identity.expectedHeadChangeId, generation: writer.generation, interruptedAt: this.now(), reason }, operations: record.operations.map((item) => item.operationId === operationId ? { ...item, outcome: { phase: "unknown", stoppedAt: this.now(), reason } } : item), updatedAt: this.now() }; }); }
  private async readId(path: string, revision: string) { return changeId(await this.read(path, ["log", "--revision", revision, "--no-graph", "--template", ID_TEMPLATE])); }
  private readOperationId(path: string) { return this.read(path, ["--ignore-working-copy", "operation", "log", "--limit", "1", "--no-graph", "--template", 'id ++ "\\n"']); }
  private async read(path: string, args: readonly string[]): Promise<string> { const result = await this.options.executor.execute({ cwd: absolutePath(path), args, access: "read" }); if (result.kind !== "success") throw new Error(result.stderr.trim() || renderJjExecutionFailure(result.failure)); const value = result.stdout.trim(); if (!value || value.includes("\n")) throw new Error("Expected exactly one JJ result."); return value; }
}
function unsettledClaims(record: Extract<PersistedIsolatedWorkspaceV1, { phase: "active" }>) { return record.claims.filter((claim) => claim.phase !== "released"); }
function startedOperation(operationId: string, kind: PersistedWorkspaceOperationV1["kind"], idempotencyKey: string, startedAt: string, beforeJjOperationId: string, intent: unknown): PersistedWorkspaceOperationV1 { return { operationId, kind, idempotencyKey, startedAt, beforeJjOperationId, intent, outcome: { phase: "started", boundary: "prepared" } }; }
function completeOperation(operations: readonly PersistedWorkspaceOperationV1[], operationId: string, afterJjOperationId: string, receipt: unknown, at: string): PersistedWorkspaceOperationV1[] { return operations.map((item) => item.operationId === operationId ? { ...item, outcome: { phase: "completed", completedAt: at, afterJjOperationId, receipt } } : item); }
function sha(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function asRecord(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("Operation intent must be an object."); return value as Record<string, unknown>; }
function requiredString(value: unknown, label: string): string { if (typeof value !== "string" || !value) throw new Error(`${label} is required.`); return value; }
function requiredStrings(value: unknown, label: string): string[] { if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) throw new Error(`${label} must be a string array.`); return value as string[]; }
