import { createHash, randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { changeId, jjOperationId, sourceWorkspaceHandle, sourceWorkspaceId, type WorkspaceId } from "./domain.ts";
import type { ReviewService } from "../concurrency/reviews.ts";
import type { IntegrationReceipt } from "./operations.ts";
import { exactChange, type JjRepositoryKernel } from "./repository.ts";
import { updateStaleSafely } from "./stale-update.ts";
import type { IsolatedWorkspaceStore, PersistedIntegrationAttemptV1, PersistedIsolatedWorkspaceV1 } from "./workspace-persistence.ts";
import type { JjWorkspaceRepositoryKernel } from "./workspace-repository.ts";

export interface VerifiedIntegrationReceipt extends IntegrationReceipt { readonly approvalId: string; readonly orderedChangeIds: readonly string[]; readonly normalizedPatchHash: string; readonly sourcePatchHash: string; readonly conflictPaths: readonly string[]; readonly conflictOwnership: Readonly<Record<string, readonly string[]>>; readonly completedAt: string; }
export class WorkspaceIntegrationService {
  private readonly workspaces: IsolatedWorkspaceStore; private readonly reviews: ReviewService; private readonly sources: JjRepositoryKernel; private readonly repository: JjWorkspaceRepositoryKernel; private readonly now: () => string; private readonly failpoint?: (operation: string, boundary: string) => void;
  constructor(options: { workspaces: IsolatedWorkspaceStore; reviews: ReviewService; sources: JjRepositoryKernel; repository: JjWorkspaceRepositoryKernel; now?: () => string; failpoint?: (operation: string, boundary: string) => void }) { this.workspaces = options.workspaces; this.reviews = options.reviews; this.sources = options.sources; this.repository = options.repository; this.now = options.now ?? (() => new Date().toISOString()); this.failpoint = options.failpoint; }
  async integrate(id: WorkspaceId): Promise<VerifiedIntegrationReceipt> { const record = await this.workspaces.get(id); if (!record || record.phase !== "approved") throw new Error("Workspace is not approved for integration."); const approval = await this.reviews.requireApproval(record.reviewId); if (approval.receiptDigest !== (record.approval as any).receiptDigest) throw new Error("Workspace approval identity mismatch."); const source = sourceWorkspaceHandle(sourceWorkspaceId(record.identity.sourceId)); const inspection = await this.sources.inspect(source); if (inspection.current.changeId !== record.identity.sourceWipChangeId) throw new Error("Source WIP identity changed before integration."); const sourcePatchHash = hash(await this.sources.patchEvidence(source, exactChange(inspection.current.changeId))); const entries = await this.repository.range(id, changeId(record.identity.rootChangeId), changeId(record.identity.expectedHeadChangeId)); const rangeEntries = entries.filter((entry) => entry.changeId !== record.identity.expectedHeadChangeId); if (rangeEntries.map((entry) => entry.changeId).join() !== approval.orderedChangeIds.join()) throw new Error("Approved range no longer matches the exact workspace range."); const emptyIds = entries.filter((entry) => entry.empty).map((entry) => entry.changeId); const nonempty = rangeEntries.filter((entry) => !entry.empty); const attempt: PersistedIntegrationAttemptV1 = { integrationId: `integration-${randomUUID()}`, approvalId: approval.approvalId, operationId: `jjop-${randomUUID()}`, phase: "prepared", sourceWipChangeId: inspection.current.changeId, sourcePatchHash, orderedChangeIds: nonempty.map((entry) => entry.changeId), emptyChangeIds: emptyIds, startedAt: this.now(), lastEvidence: { jjOperationId: inspection.jjOperationId } }; await this.workspaces.update(id, (current) => current.phase !== "approved" ? current : { ...current, phase: "integrating", attempt, updatedAt: this.now() }); return this.continueIntegration(id); }
  async resume(id: WorkspaceId): Promise<VerifiedIntegrationReceipt> { const record = await this.workspaces.get(id); if (!record || record.phase !== "integrating") throw new Error("Workspace has no resumable integration attempt."); if (record.attempt.phase === "unknown") throw new Error("Integration has unknown partial mutation and requires attention."); return this.continueIntegration(id); }
  private async continueIntegration(id: WorkspaceId): Promise<VerifiedIntegrationReceipt> { const initial = await this.workspaces.get(id); if (!initial || initial.phase !== "integrating") throw new Error("Workspace integration custody disappeared."); const source = sourceWorkspaceHandle(sourceWorkspaceId(initial.identity.sourceId)); const approval = await this.reviews.requireApproval(initial.reviewId); try { return await this.sources.withRepositoryMutation(source, async () => {
      let record = await this.requireIntegrating(id); let phase = record.attempt.phase;
      const sourceCurrent = await this.sources.currentChangeId(source); if (sourceCurrent !== record.attempt.sourceWipChangeId) throw new Error("Source WIP changed during integration.");
      if (phase === "prepared") { await this.sources.runMutation(source, ["workspace", "forget", record.identity.name]); await this.advance(id, "workspace_detached", { workspaceName: record.identity.name }); this.trigger("workspace_detached"); phase = "workspace_detached"; }
      record = await this.requireIntegrating(id);
      if (phase === "workspace_detached") { for (const empty of record.attempt.emptyChangeIds) await this.abandonIfPresent(source, empty); await this.advance(id, "empties_removed", { removed: record.attempt.emptyChangeIds }); this.trigger("empties_removed"); phase = "empties_removed"; }
      record = await this.requireIntegrating(id);
      if (phase === "empties_removed") { const union = record.attempt.orderedChangeIds.map((item) => exactChange(changeId(item))).join(" | "); await this.sources.runMutation(source, ["--ignore-working-copy", "rebase", "--revision", union, "--insert-before", exactChange(changeId(record.attempt.sourceWipChangeId))]); await updateStaleSafely({ context: "Integration", location: "the source workspace", read: (args) => this.sources.readOnly(source, args), run: (args) => this.sources.runMutation(source, args) }); await this.advance(id, "range_inserted", { ordered: record.attempt.orderedChangeIds }); this.trigger("range_inserted"); phase = "range_inserted"; }
      record = await this.requireIntegrating(id);
      let conflicts: string[] = []; let conflictOwnership: Record<string, string[]> = {};
      if (phase === "range_inserted") { for (const change of record.attempt.orderedChangeIds) { const resolved = await this.sources.resolveChange(source, changeId(change)); if (!resolved.description.trim()) throw new Error(`Integrated change ${change} is unnamed.`); if (resolved.conflicted) { const paths = await this.sources.conflictPaths(source, exactChange(changeId(change))); for (const path of paths) { conflicts.push(path); conflictOwnership[path] = [...(conflictOwnership[path] ?? []), change]; } } } const sourceAfter = await this.sources.currentChangeId(source); if (sourceAfter !== record.attempt.sourceWipChangeId || hash(await this.sources.patchEvidence(source, exactChange(sourceAfter))) !== record.attempt.sourcePatchHash) throw new Error("Integration changed source WIP identity or content."); const patchHash = hash(await this.sources.patchEvidence(source, `${exactChange(changeId(record.attempt.orderedChangeIds[0]!))}::${exactChange(changeId(record.attempt.orderedChangeIds.at(-1)!))}`)); if (!conflicts.length && patchHash !== approval.normalizedPatchHash) throw new Error("Integrated normalized patch differs from approval."); await this.advance(id, "graph_verified", { patchHash, conflicts: [...new Set(conflicts)].sort(), conflictOwnership }); this.trigger("graph_verified"); phase = "graph_verified"; }
      record = await this.requireIntegrating(id); const evidence = record.attempt.lastEvidence as any; conflicts = Array.isArray(evidence.conflicts) ? evidence.conflicts : conflicts; conflictOwnership = evidence.conflictOwnership && typeof evidence.conflictOwnership === "object" ? evidence.conflictOwnership : conflictOwnership;
      const receipt: VerifiedIntegrationReceipt = { workspaceId: id, integratedChangeIds: record.attempt.orderedChangeIds.map(changeId), sourceWipChangeId: changeId(record.attempt.sourceWipChangeId), conflicted: conflicts.length > 0, operationId: jjOperationId(record.attempt.operationId), approvalId: record.attempt.approvalId, orderedChangeIds: record.attempt.orderedChangeIds, normalizedPatchHash: String(evidence.patchHash ?? approval.normalizedPatchHash), sourcePatchHash: record.attempt.sourcePatchHash, conflictPaths: [...new Set(conflicts)].sort(), conflictOwnership, completedAt: this.now() };
      if (conflicts.length) { await this.workspaces.update(id, (current) => current.phase !== "integrating" ? current : { ...current, phase: "conflict_resolution", integrationReceipt: receipt, conflictPaths: conflicts, updatedAt: this.now() }); return receipt; }
      if (phase === "graph_verified") { await rm(record.identity.path, { recursive: true, force: true }); await this.advance(id, "directory_removed", { removedPath: record.identity.path }); this.trigger("directory_removed"); }
      await this.workspaces.update(id, (current) => current.phase !== "integrating" ? current : { ...current, phase: "integrated", integrationReceipt: receipt, updatedAt: this.now() }); return receipt;
    }); } catch (error) { if (!(error instanceof KnownBoundaryInterruption)) await this.workspaces.update(id, (record) => record.phase !== "integrating" ? record : { ...record, attempt: { ...record.attempt, phase: "unknown", lastEvidence: { prior: record.attempt.lastEvidence, reason: error instanceof Error ? error.message : String(error) } }, updatedAt: this.now() }); throw error; } }
  private trigger(boundary: string): void { try { this.failpoint?.("integrate_workspace", boundary); } catch (error) { throw new KnownBoundaryInterruption(error instanceof Error ? error.message : String(error)); } }
  private async requireIntegrating(id: WorkspaceId) { const value = await this.workspaces.get(id); if (!value || value.phase !== "integrating") throw new Error("Workspace is not integrating."); return value; }
  private async advance(id: WorkspaceId, phase: PersistedIntegrationAttemptV1["phase"], lastEvidence: unknown): Promise<void> { await this.workspaces.update(id, (record) => record.phase !== "integrating" ? record : { ...record, attempt: { ...record.attempt, phase, lastEvidence }, updatedAt: this.now() }); }
  private async abandonIfPresent(source: ReturnType<typeof sourceWorkspaceHandle>, id: string): Promise<void> { try { await this.sources.runMutation(source, ["--ignore-working-copy", "abandon", exactChange(changeId(id))]); } catch (error) { if (!String(error).includes("got 0")) throw error; } }
}
class KnownBoundaryInterruption extends Error {}
function hash(value: string): string { return createHash("sha256").update(value).digest("hex"); }
