import { createHash, randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { changeId, sourceWorkspaceHandle, sourceWorkspaceId, type WorkspaceId } from "./domain.ts";
import { exactChange, type JjRepositoryKernel } from "./repository.ts";
import type { IsolatedWorkspaceStore } from "./workspace-persistence.ts";
import type { UserMessageEvidenceV1 } from "../concurrency/tasks.ts";
import type { WorkspaceIntegrationService } from "./workspace-integration.ts";

export interface WorkspaceVerificationReceipt { readonly verificationId: string; readonly workspaceId: string; readonly integrationId: string; readonly jjEvidenceDigest: string; readonly productChecks: readonly string[]; readonly verifiedAt: string; }
export interface RecoveryAuthorizationV1 { readonly authorizationId: string; readonly workspaceId: string; readonly action: "resume_operation" | "retry_cleanup" | "rebind_change"; readonly userEvidence: UserMessageEvidenceV1; readonly createdAt: string; }
export class WorkspaceClosureService {
  private readonly workspaces: IsolatedWorkspaceStore; private readonly sources: JjRepositoryKernel; private readonly integration: WorkspaceIntegrationService; private readonly now: () => string;
  constructor(workspaces: IsolatedWorkspaceStore, sources: JjRepositoryKernel, integration: WorkspaceIntegrationService, now = () => new Date().toISOString()) { this.workspaces = workspaces; this.sources = sources; this.integration = integration; this.now = now; }
  async verify(id: WorkspaceId, productChecks: readonly string[]): Promise<WorkspaceVerificationReceipt> { const record = await this.workspaces.get(id); if (!record || record.phase !== "integrated") throw new Error("Workspace is not semantically integrated."); const receipt = record.integrationReceipt as any; if (receipt.conflicted) throw new Error("Conflicted integration requires focused repair and review before verification."); const source = sourceWorkspaceHandle(sourceWorkspaceId(record.identity.sourceId)); const sourceHead = await this.sources.currentChangeId(source); if (sourceHead !== receipt.sourceWipChangeId) throw new Error("Source WIP identity changed after integration."); const resolved = []; for (const item of receipt.orderedChangeIds as string[]) { const change = await this.sources.resolveChange(source, changeId(item)); if (change.conflicted || !change.description.trim()) throw new Error(`Integrated change ${item} is not clean and named.`); resolved.push({ id: item, parents: change.parentChangeIds, description: change.description }); } const patch = await this.sources.patchEvidence(source, `${exactChange(changeId(receipt.orderedChangeIds[0]))}::${exactChange(changeId(receipt.orderedChangeIds.at(-1)))}`); if (createHash("sha256").update(patch).digest("hex") !== receipt.normalizedPatchHash) throw new Error("Integrated patch no longer matches integration receipt."); if (!productChecks.length || productChecks.some((item) => !item.trim())) throw new Error("Product verification requires nonempty acceptance evidence."); const verification: WorkspaceVerificationReceipt = { verificationId: `verification-${randomUUID()}`, workspaceId: id, integrationId: String(receipt.operationId), jjEvidenceDigest: createHash("sha256").update(JSON.stringify(resolved)).digest("hex"), productChecks, verifiedAt: this.now() }; await this.workspaces.update(id, (current) => current.phase !== "integrated" ? current : { ...current, phase: "verifying", verificationId: verification.verificationId, verificationReceipt: verification, updatedAt: this.now() }); return verification; }
  async close(id: WorkspaceId): Promise<void> { await this.workspaces.update(id, (record) => { if (record.phase !== "verifying") throw new Error("Workspace verification receipt does not match custody."); return { ...record, phase: "closed", closedAt: this.now(), updatedAt: this.now() }; }); }
  async resume(id: WorkspaceId, authorization: RecoveryAuthorizationV1) { this.authorize(id, authorization, "resume_operation"); return this.integration.resume(id); }
  async rebind(id: WorkspaceId, input: { kind: "root" | "head"; replacementChangeId: string; authorization: RecoveryAuthorizationV1 }): Promise<unknown> { this.authorize(id, input.authorization, "rebind_change"); const record = await this.workspaces.get(id); if (!record || record.phase !== "incident" || !record.identity) throw new Error("Only incident custody with tracked identity can be rebound."); const replacement = changeId(input.replacementChangeId); const source = sourceWorkspaceHandle(sourceWorkspaceId(record.identity.sourceId)); await this.sources.resolveChange(source, replacement); if (input.kind === "head" && !await this.sources.isAncestor(source, changeId(record.identity.rootChangeId), replacement)) throw new Error("Replacement head is disconnected from tracked root."); if (input.kind === "root" && !await this.sources.isAncestor(source, changeId(record.identity.baseChangeId), replacement)) throw new Error("Replacement root is disconnected from tracked base."); const receipt = { authorizationId: input.authorization.authorizationId, kind: input.kind, priorChangeId: input.kind === "root" ? record.identity.rootChangeId : record.identity.expectedHeadChangeId, replacementChangeId: replacement, reboundAt: this.now() }; await this.workspaces.update(id, (current) => current.phase !== "incident" || !current.identity ? current : { ...current, identity: { ...current.identity, ...(input.kind === "root" ? { rootChangeId: replacement } : { expectedHeadChangeId: replacement }) }, evidence: { prior: current.evidence, rebindReceipt: receipt }, updatedAt: this.now() }); return receipt; }
  async retryCleanup(id: WorkspaceId, authorization: RecoveryAuthorizationV1): Promise<void> { this.authorize(id, authorization, "retry_cleanup"); const record = await this.workspaces.get(id); if (!record || record.phase !== "cleanup_pending") throw new Error("Workspace has no cleanup-pending custody."); await rm(record.identity.path, { recursive: true, force: true }); const prior = (record.semanticReceipt as any)?.priorRecord; if (!prior || (prior.phase !== "closed" && prior.phase !== "closed_no_changes")) throw new Error("Cleanup receipt cannot reconstruct semantic closure."); await this.workspaces.update(id, () => ({ ...prior, updatedAt: this.now() })); }
  private authorize(id: WorkspaceId, authorization: RecoveryAuthorizationV1, action: RecoveryAuthorizationV1["action"]): void { if (authorization.workspaceId !== id || authorization.action !== action || authorization.userEvidence.contentHash !== createHash("sha256").update(authorization.userEvidence.content).digest("hex")) throw new Error("Recovery requires matching sourced user authorization."); }
}
