import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { type WorkspaceId } from "./domain.ts";
import type { IsolatedWorkspaceStore, PersistedWorkspaceReportV1 } from "./workspace-persistence.ts";
import type { ReviewApprovalReceiptV1, ReviewBundleV1, ReviewerReportV1, ReviewService, FindingDispositionV1 } from "../concurrency/reviews.ts";
import type { TaskService } from "../concurrency/tasks.ts";

export class WorkspaceReviewCoordinator {
  private readonly workspaces: IsolatedWorkspaceStore; private readonly reviews: ReviewService; private readonly tasks: TaskService; private readonly now: () => string;
  constructor(workspaces: IsolatedWorkspaceStore, reviews: ReviewService, tasks: TaskService, now = () => new Date().toISOString()) { this.workspaces = workspaces; this.reviews = reviews; this.tasks = tasks; this.now = now; }
  async status(id: WorkspaceId): Promise<unknown> { const workspace = await this.workspaces.get(id); if (!workspace) throw new Error(`Unknown workspace: ${id}`); const directReviewId = "reviewId" in workspace && typeof workspace.reviewId === "string" ? workspace.reviewId : undefined; const prior = "priorReviewIds" in workspace && Array.isArray(workspace.priorReviewIds) ? workspace.priorReviewIds.at(-1) : undefined; const reviewId = directReviewId ?? prior; const review = reviewId ? await this.reviews.status(reviewId) : undefined; return { workspaceId: id, workspacePhase: workspace.phase, reviewId, review, approvalEligible: review?.phase === "reported" && !review.report.findings.some((finding) => finding.severity === "p0" || finding.severity === "p1"), blockingFindings: review?.phase === "reported" || review?.phase === "approved" ? review.report.findings.filter((finding) => finding.severity === "p0" || finding.severity === "p1") : [], unresolvedP2: review?.phase === "reported" ? review.report.findings.filter((finding) => finding.severity === "p2") : [] }; }
  async acknowledge(id: WorkspaceId, input: { implementationEventId: string; taskId: string }): Promise<void> { await this.workspaces.update(id, (record) => { if (record.phase !== "reported") throw new Error("Only a reported workspace can be acknowledged."); if (record.report.range === "empty") return { version: 1, phase: "closed_no_changes", identity: record.identity, proof: record.report, taskId: input.taskId, closedAt: this.now(), createdAt: record.createdAt, updatedAt: this.now() }; return { ...record, phase: "acknowledged", reportVersion: record.reportVersion ?? 1, implementationEventId: input.implementationEventId, taskId: input.taskId, updatedAt: this.now() }; }); }
  async prepareReview(id: WorkspaceId): Promise<ReviewBundleV1> { const record = await this.workspaces.get(id); if (!record || record.phase !== "acknowledged" || record.report.range !== "nonempty") throw new Error("Workspace is not acknowledged with a nonempty report."); const taskSnapshot = await this.tasks.snapshot(record.taskId); const evidence = await reportEvidence(record.report); const bundle = await this.reviews.prepare({ workspaceId: id, reportVersion: record.reportVersion, taskSnapshot, rootChangeId: record.identity.rootChangeId, workspaceHeadChangeId: record.identity.expectedHeadChangeId, contentTipChangeId: record.report.contentTipChangeId, orderedChangeIds: evidence.orderedChangeIds, normalizedPatchHash: record.report.normalizedPatchHash, conflictPaths: evidence.conflictPaths, evidenceDigest: hash(evidence) }); await this.workspaces.update(id, (current) => current.phase !== "acknowledged" ? current : { ...current, phase: "reviewing", reviewId: bundle.bundleId, reviewCycle: record.reviewCycle ?? 0, updatedAt: this.now() }); return bundle; }
  async submitReview(id: WorkspaceId, input: Omit<ReviewerReportV1, "reviewId" | "bundleId" | "submittedAt" | "cycle">): Promise<ReviewerReportV1> { const record = await this.workspaces.get(id); if (!record || record.phase !== "reviewing") throw new Error("Workspace is not under review."); const report = await this.reviews.submit(record.reviewId, { ...input, cycle: record.reviewCycle }); if (report.findings.some((item) => item.severity === "p0" || item.severity === "p1")) await this.workspaces.update(id, (current) => current.phase !== "reviewing" ? current : { ...current, phase: "changes_requested", updatedAt: this.now() }); return report; }
  async approve(id: WorkspaceId, input: { orchestratorContextId: string; dispositions: readonly FindingDispositionV1[] }): Promise<ReviewApprovalReceiptV1> { const record = await this.workspaces.get(id); if (!record || record.phase !== "reviewing") throw new Error("Workspace is not awaiting review approval."); const bundle = await this.reviews.requireBundle(record.reviewId); const currentTaskSnapshot = await this.tasks.snapshot(record.taskId); if (currentTaskSnapshot.digest !== bundle.taskSnapshot.digest) { await this.workspaces.update(id, (current) => { if (current.phase !== "reviewing" || current.reviewId !== record.reviewId) return current; const { reviewId, ...rest } = current; return { ...rest, phase: "acknowledged", priorReviewIds: [...(current.priorReviewIds ?? []), reviewId], updatedAt: this.now() }; }); throw new Error("Review task snapshot is stale after a task-plan or user-direction change; prepare a new review."); } await this.tasks.requireImplementationPlan(record.taskId); const approval = await this.reviews.approve(record.reviewId, { approvedByContextId: input.orchestratorContextId, dispositions: input.dispositions }); const currentEvidence = await reportEvidence(record.report); if (approval.evidenceDigest !== hash(currentEvidence) || approval.normalizedPatchHash !== (record.report.range === "nonempty" ? record.report.normalizedPatchHash : "")) throw new Error("Review approval is stale for the frozen workspace report."); await this.workspaces.update(id, (current) => current.phase !== "reviewing" ? current : { ...current, phase: "approved", approval, updatedAt: this.now() }); return approval; }
  async prepareConflictReview(id: WorkspaceId): Promise<ReviewBundleV1> { const record = await this.workspaces.get(id); if (!record || record.phase !== "conflict_resolution" || record.conflictPaths.length) throw new Error("Owned conflicts must be resolved before focused review."); const integration = record.integrationReceipt as any; if (!integration.resolutionReceipt) throw new Error("Conflict resolution receipt is missing."); const taskSnapshot = await this.tasks.snapshot(record.taskId); const ordered = integration.orderedChangeIds as string[]; if (!ordered.length) throw new Error("Conflict review requires integrated changes."); const bundle = await this.reviews.prepare({ workspaceId: id, reportVersion: record.reportVersion + 1, taskSnapshot, rootChangeId: ordered[0]!, workspaceHeadChangeId: record.identity.expectedHeadChangeId, contentTipChangeId: ordered.at(-1)!, orderedChangeIds: ordered, normalizedPatchHash: integration.normalizedPatchHash, conflictPaths: [], evidenceDigest: hash(integration.resolutionReceipt) }); await this.workspaces.update(id, (current) => current.phase !== "conflict_resolution" ? current : { ...current, focusedReviewId: bundle.bundleId, updatedAt: this.now() }); return bundle; }
  async submitConflictReview(id: WorkspaceId, input: Omit<ReviewerReportV1, "reviewId" | "bundleId" | "submittedAt" | "cycle">): Promise<ReviewerReportV1> { const record = await this.workspaces.get(id); if (!record || record.phase !== "conflict_resolution" || !record.focusedReviewId) throw new Error("Conflict custody has no focused review."); return this.reviews.submit(record.focusedReviewId, { ...input, cycle: 1 }); }
  async approveConflictReview(id: WorkspaceId, input: { orchestratorContextId: string; dispositions: readonly FindingDispositionV1[] }): Promise<ReviewApprovalReceiptV1> { const record = await this.workspaces.get(id); if (!record || record.phase !== "conflict_resolution" || !record.focusedReviewId) throw new Error("Conflict custody has no focused review."); const focusedReviewId = record.focusedReviewId; const bundle = await this.reviews.requireBundle(focusedReviewId); const currentTaskSnapshot = await this.tasks.snapshot(record.taskId); if (currentTaskSnapshot.digest !== bundle.taskSnapshot.digest) { await this.workspaces.update(id, (current) => { if (current.phase !== "conflict_resolution" || current.focusedReviewId !== focusedReviewId) return current; const { focusedReviewId: staleReviewId, ...rest } = current; return { ...rest, priorReviewIds: [...(current.priorReviewIds ?? []), staleReviewId!], updatedAt: this.now() }; }); throw new Error("Focused review task snapshot is stale after a task-plan or user-direction change; prepare a new focused review."); } await this.tasks.requireImplementationPlan(record.taskId); const approval = await this.reviews.approve(record.focusedReviewId, { approvedByContextId: input.orchestratorContextId, dispositions: input.dispositions }); await this.workspaces.update(id, (current) => current.phase !== "conflict_resolution" ? current : { ...current, phase: "integrated", approval, integrationReceipt: { ...(current.integrationReceipt as any), focusedReviewApproval: approval }, updatedAt: this.now() }); return approval; }
  async beginRepair(id: WorkspaceId): Promise<void> { await this.workspaces.update(id, (record) => { if (record.phase !== "changes_requested") throw new Error("Workspace has no blocking review findings."); if (record.reviewCycle >= 1) throw new Error("Automatic workspace repair budget is exhausted."); return { version: 1, phase: "active", identity: record.identity, writer: { phase: "available", headChangeId: record.identity.expectedHeadChangeId, generation: 0 }, targets: [], claims: [], operations: record.operations, reviewCycle: record.reviewCycle + 1, priorReviewIds: [...(record.priorReviewIds ?? []), record.reviewId], createdAt: record.createdAt, updatedAt: this.now() }; }); }
}

async function reportEvidence(report: PersistedWorkspaceReportV1): Promise<{ orderedChangeIds: string[]; conflictPaths: string[] }> { if (report.evidence === "inline") return { orderedChangeIds: [...report.orderedChangeIds], conflictPaths: [...(report.conflictPaths ?? [])] }; const parsed: unknown = JSON.parse(await readFile(report.artifact.path, "utf8")); if (!object(parsed) || !Array.isArray(parsed.orderedChangeIds) || !Array.isArray(parsed.conflictPaths)) throw new Error("Workspace range artifact is invalid."); const digest = createHash("sha256").update(await readFile(report.artifact.path)).digest("hex"); if (digest !== report.artifact.digest) throw new Error("Workspace range artifact digest mismatch."); return { orderedChangeIds: parsed.orderedChangeIds.map(String), conflictPaths: parsed.conflictPaths.map(String) }; }
function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function object(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value); }
