import { createHash, randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { changeId, sourceWorkspaceHandle, sourceWorkspaceId, type WorkspaceId } from "./domain.ts";
import { exactChange, type JjRepositoryKernel } from "./repository.ts";
import type { IsolatedWorkspaceStore } from "./workspace-persistence.ts";
import type { WorkspaceIntegrationService } from "./workspace-integration.ts";

export type DocumentationDisposition = { readonly kind: "updated"; readonly paths: readonly string[]; readonly evidence: string } | { readonly kind: "not_required"; readonly rationale: string };
export interface WorkspaceVerificationReceipt { readonly verificationId: string; readonly workspaceId: string; readonly integrationId: string; readonly jjEvidenceDigest: string; readonly productChecks: readonly string[]; readonly documentation: DocumentationDisposition; readonly verifiedAt: string; }
export class WorkspaceClosureService {
  private readonly workspaces: IsolatedWorkspaceStore; private readonly sources: JjRepositoryKernel; private readonly integration: WorkspaceIntegrationService; private readonly now: () => string;
  constructor(workspaces: IsolatedWorkspaceStore, sources: JjRepositoryKernel, integration: WorkspaceIntegrationService, now = () => new Date().toISOString()) { this.workspaces = workspaces; this.sources = sources; this.integration = integration; this.now = now; }
  async verify(id: WorkspaceId, productChecks: readonly string[], documentation: DocumentationDisposition = { kind: "not_required", rationale: "Legacy caller supplied no documentation disposition." }): Promise<WorkspaceVerificationReceipt> { const record = await this.workspaces.get(id); if (!record || record.phase !== "integrated") throw new Error("Workspace is not semantically integrated."); const receipt = record.integrationReceipt as any; if (receipt.conflicted) throw new Error("Conflicted integration requires focused repair and review before verification."); const source = sourceWorkspaceHandle(sourceWorkspaceId(record.identity.sourceId)); const resolved = []; for (const item of receipt.orderedChangeIds as string[]) { const change = await this.sources.resolveChange(source, changeId(item)); if (change.conflicted || !change.description.trim()) throw new Error(`Integrated change ${item} is not clean and named.`); resolved.push({ id: item, parents: change.parentChangeIds, description: change.description }); } const patch = await this.sources.patchEvidence(source, `${exactChange(changeId(receipt.orderedChangeIds[0]))}::${exactChange(changeId(receipt.orderedChangeIds.at(-1)))}`); if (createHash("sha256").update(patch).digest("hex") !== receipt.normalizedPatchHash) throw new Error("Integrated patch no longer matches integration receipt."); if (!productChecks.length || productChecks.some((item) => !item.trim())) throw new Error("Product verification requires nonempty acceptance evidence."); if (documentation.kind === "updated") { if (!documentation.paths.length || documentation.paths.some((path) => !path.trim()) || !documentation.evidence.trim()) throw new Error("Updated documentation disposition requires paths and evidence."); } else if (!documentation.rationale.trim()) throw new Error("Documentation not-required disposition requires a rationale."); const verification: WorkspaceVerificationReceipt = { verificationId: `verification-${randomUUID()}`, workspaceId: id, integrationId: String(receipt.operationId), jjEvidenceDigest: createHash("sha256").update(JSON.stringify(resolved)).digest("hex"), productChecks, documentation, verifiedAt: this.now() }; await this.workspaces.update(id, (current) => current.phase !== "integrated" ? current : { ...current, phase: "verifying", verificationId: verification.verificationId, verificationReceipt: verification, updatedAt: this.now() }); return verification; }
  async close(id: WorkspaceId): Promise<void> { await this.workspaces.update(id, (record) => { if (record.phase !== "verifying") throw new Error("Workspace verification receipt does not match custody."); return { ...record, phase: "closed", closedAt: this.now(), updatedAt: this.now() }; }); }
  async resume(id: WorkspaceId) { return this.integration.resume(id); }
  async rebind(id: WorkspaceId, input: { kind: "root" | "head"; replacementChangeId: string }): Promise<unknown> { const record = await this.workspaces.get(id); if (!record || record.phase !== "incident" || !record.identity) throw new Error("Only incident custody with tracked identity can be rebound."); const replacement = changeId(input.replacementChangeId); const source = sourceWorkspaceHandle(sourceWorkspaceId(record.identity.sourceId)); await this.sources.resolveChange(source, replacement); if (input.kind === "head" && !await this.sources.isAncestor(source, changeId(record.identity.rootChangeId), replacement)) throw new Error("Replacement head is disconnected from tracked root."); if (input.kind === "root" && !await this.sources.isAncestor(source, replacement, changeId(record.identity.expectedHeadChangeId))) throw new Error("Replacement root is disconnected from tracked workspace head."); const receipt = { rebindId: `rebind-${randomUUID()}`, kind: input.kind, priorChangeId: input.kind === "root" ? record.identity.rootChangeId : record.identity.expectedHeadChangeId, replacementChangeId: replacement, reboundAt: this.now() }; await this.workspaces.update(id, (current) => current.phase !== "incident" || !current.identity ? current : { ...current, identity: { ...current.identity, ...(input.kind === "root" ? { rootChangeId: replacement } : { expectedHeadChangeId: replacement }) }, evidence: { prior: current.evidence, rebindReceipt: receipt }, updatedAt: this.now() }); return receipt; }
  async retryCleanup(id: WorkspaceId): Promise<void> { const record = await this.workspaces.get(id); if (!record || record.phase !== "cleanup_pending") throw new Error("Workspace has no cleanup-pending custody."); await rm(record.identity.path, { recursive: true, force: true }); const prior = (record.semanticReceipt as any)?.priorRecord; if (!prior || (prior.phase !== "closed" && prior.phase !== "closed_no_changes")) throw new Error("Cleanup receipt cannot reconstruct semantic closure."); await this.workspaces.update(id, () => ({ ...prior, updatedAt: this.now() })); }
}
