import { createHash, randomUUID } from "node:crypto";
import { changeId, sourceWorkspaceHandle, sourceWorkspaceId, type ConflictResolutionLease } from "./domain.ts";
import { exactChange, literalRootFileset, type JjRepositoryKernel } from "./repository.ts";
import type { IsolatedWorkspaceStore } from "./workspace-persistence.ts";

export interface ConflictResolutionReceipt { readonly resolutionId: string; readonly workspaceId: string; readonly resolvedPaths: readonly string[]; readonly owningChangeIds: readonly string[]; readonly patchHash: string; readonly focusedReviewRequired: true; readonly completedAt: string; }
export class WorkspaceConflictService {
  private readonly workspaces: IsolatedWorkspaceStore; private readonly sources: JjRepositoryKernel; private readonly now: () => string;
  constructor(workspaces: IsolatedWorkspaceStore, sources: JjRepositoryKernel, now = () => new Date().toISOString()) { this.workspaces = workspaces; this.sources = sources; this.now = now; }
  async squashResolution(lease: ConflictResolutionLease, paths: readonly string[]): Promise<ConflictResolutionReceipt> { const record = await this.workspaces.get(lease.workspaceId); if (!record || record.phase !== "conflict_resolution") throw new Error("Workspace has no owned integration conflict custody."); const integration = record.integrationReceipt as any; const ownership = integration.conflictOwnership as Record<string, string[]>; const unique = [...new Set(paths)].sort(); if (!unique.length) throw new Error("Conflict resolution requires paths."); const byOwner = new Map<string, string[]>(); for (const path of unique) { const owners = ownership[path]; if (!owners || owners.length !== 1) throw new Error(`Conflict path ${path} does not have one unique owning change.`); byOwner.set(owners[0]!, [...(byOwner.get(owners[0]!) ?? []), path]); }
    const source = sourceWorkspaceHandle(sourceWorkspaceId(record.identity.sourceId)); await this.sources.withRepositoryMutation(source, async () => { for (const [owner, ownedPaths] of byOwner) await this.sources.runMutation(source, ["--ignore-working-copy", "squash", "--from", "@", "--into", exactChange(changeId(owner)), ...ownedPaths.map(literalRootFileset)]); });
    const remaining: string[] = []; for (const owner of byOwner.keys()) remaining.push(...await this.sources.conflictPaths(source, exactChange(changeId(owner)))); if (remaining.length) throw new Error(`Conflict resolution remains incomplete: ${[...new Set(remaining)].join(", ")}`); const first = integration.orderedChangeIds[0], last = integration.orderedChangeIds.at(-1); const patch = await this.sources.patchEvidence(source, `${exactChange(changeId(first))}::${exactChange(changeId(last))}`); const receipt: ConflictResolutionReceipt = { resolutionId: `resolution-${randomUUID()}`, workspaceId: lease.workspaceId, resolvedPaths: unique, owningChangeIds: [...byOwner.keys()], patchHash: createHash("sha256").update(patch).digest("hex"), focusedReviewRequired: true, completedAt: this.now() }; await this.workspaces.update(lease.workspaceId, (current) => current.phase !== "conflict_resolution" ? current : { ...current, integrationReceipt: { ...integration, conflicted: false, conflictPaths: [], normalizedPatchHash: receipt.patchHash, resolutionReceipt: receipt }, conflictPaths: [], updatedAt: this.now() }); return receipt; }
}
