import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "../..");
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
  keywords?: string[];
  pi?: { extensions?: string[]; prompts?: string[]; themes?: string[]; skills?: string[] };
  dependencies?: Record<string, string>;
  files?: string[];
};

test("root manifest is a discoverable Pi package", () => {
  assert.ok(manifest.keywords?.includes("pi-package"));
  assert.deepEqual(manifest.pi?.extensions, ["./packages/pi-tai/pi-tai.ts"]);
  assert.deepEqual(manifest.pi?.themes, ["./packages/pi-tai/themes"]);
  assert.deepEqual(manifest.pi?.prompts, ["./packages/pi-tai/prompts"]);
  assert.deepEqual(manifest.pi?.skills, ["./packages/pi-tai/skills"]);

  for (const resource of [
    ...(manifest.pi?.extensions ?? []),
    ...(manifest.pi?.themes ?? []),
    ...(manifest.pi?.prompts ?? []),
    ...(manifest.pi?.skills ?? []),
  ]) {
    assert.ok(readFileOrDirectoryExists(join(root, resource)), resource);
  }
});

test("source uses the current Pi distribution imports", () => {
  const files = walkSource(join(root, "packages"));
  const legacy = files.filter((file) =>
    readFileSync(file, "utf8").includes("@mariozechner/"),
  );
  assert.deepEqual(legacy, []);
});

test("Pi-Tai packages a global instruction layer and declarative agent definitions", () => {
  const system = join(root, "packages/pi-tai/instructions/system.md");
  assert.ok(existsSync(system), system);
  for (const name of ["thinker", "planner", "worker", "scout", "researcher"]) {
    const path = join(root, "packages/pi-tai/agents", `${name}.md`);
    const content = readFileSync(path, "utf8");
    assert.match(content, new RegExp(`name: ${name}`));
    assert.match(content, /model: openai-codex\/gpt-5\.6-/);
    assert.match(content, /effort:/);
    assert.match(content, /tools:/);
  }
});

test("workspace is packaged as an automatic JJ-first routed skill", () => {
  const directory = join(root, "packages/pi-tai/skills/workspace");
  const skill = readFileSync(join(directory, "SKILL.md"), "utf8");
  const jj = readFileSync(join(directory, "references/jj.md"), "utf8");
  const git = readFileSync(join(directory, "references/git.md"), "utf8");
  assert.match(skill, /name: workspace/);
  assert.doesNotMatch(skill, /disable-model-invocation/);
  assert.match(skill, /workspace, work tree, worktree, isolated checkout/);
  assert.match(skill, /references\/jj\.md/);
  assert.match(skill, /references\/git\.md/);
  assert.match(jj, /source `@` to be empty/);
  assert.match(jj, /Create the isolated workspace from the source `@-`/);
  assert.match(git, /Use this strategy only when `jj root` failed/);
});

test("continue is packaged as a visible prompt template", () => {
  const prompt = readFileSync(join(root, "packages/pi-tai/prompts/continue.md"), "utf8");
  assert.match(prompt, /description: Continue the agent's previous work/);
  assert.match(prompt, /Continue what you were doing\./);
  assert.doesNotMatch(
    walkSource(join(root, "packages")).map((file) => readFileSync(file, "utf8")).join("\n"),
    /registerCommand\(["']continue["']/,
  );
});

test("legacy task blocks and permission modes are absent", () => {
  assert.equal(existsSync(join(root, "packages/pi-tai/src/modes")), false);
  assert.equal(existsSync(join(root, "packages/pi-tai/src/task-context")), false);
  const source = walkSource(join(root, "packages"))
    .map((file) => readFileSync(file, "utf8"))
    .join("\n");
  assert.doesNotMatch(source, /```task-context|@mariozechner\/|guardian-prompt\.md/);
  assert.doesNotMatch(source, /registerCommand\(["'](?:mode|review-mode|implement)/);
});

test("runtime protocol ships Rust-first DTOs and checked-in TypeScript bindings", () => {
  assert.ok(existsSync(join(root, "crates/runtime-protocol/src/lib.rs")));
  const generated = readFileSync(join(root, "packages/runtime-protocol/src/generated.ts"), "utf8");
  assert.match(generated, /@generated by pi-tai-runtime-protocol/);
  assert.match(generated, /export type RuntimeCommand/);
  assert.ok(existsSync(join(root, "packages/runtime-protocol/src/schemas.ts")));
});

test("portable Host crates remain independent of Tauri", () => {
  for (const crate of [
    "broker",
    "event-store",
    "host-kernel",
    "host-lifecycle",
    "host-platform",
    "host-protocol",
    "host-server",
    "local-ipc",
    "runtime-supervisor",
  ]) {
    const cargo = readFileSync(join(root, `crates/${crate}/Cargo.toml`), "utf8");
    assert.doesNotMatch(cargo, /tauri/i, crate);
  }
  const shellCargo = readFileSync(join(root, "apps/host/src-tauri/Cargo.toml"), "utf8");
  assert.match(shellCargo, /tauri/);
  assert.ok(existsSync(join(root, "packages/host-protocol/src/index.ts")));
  assert.ok(existsSync(join(root, "fixtures/host-protocol/command-prompt.json")));
});

test("desktop manager uses Tauri 2, Vite, React Compiler, and Tailwind", () => {
  const desktop = JSON.parse(readFileSync(join(root, "apps/host/package.json"), "utf8")) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const vite = readFileSync(join(root, "apps/host/vite.config.ts"), "utf8");
  const tauri = readFileSync(join(root, "apps/host/src-tauri/Cargo.toml"), "utf8");

  assert.equal(desktop.dependencies?.react, "19.2.8");
  assert.ok(desktop.devDependencies?.["babel-plugin-react-compiler"]);
  assert.ok(desktop.devDependencies?.tailwindcss);
  assert.match(vite, /reactCompilerPreset/);
  assert.match(vite, /tailwindcss\(\)/);
  assert.match(tauri, /tauri = \{ version = "2"/);
});

test("package ships standalone Guardian and required support files", () => {
  assert.equal(manifest.dependencies?.["pi-approval-guardian"], undefined);
  assert.ok(existsSync(join(root, "packages/pi-tai/src/guardian/reviewer.ts")));
  assert.ok(manifest.files?.includes("justfile"));
  assert.ok(existsSync(join(root, "justfile")));
  assert.doesNotMatch(readFileSync(join(root, "README.md"), "utf8"), /TEMPORARY/);
});

test("package ships web tools and their child-runtime dependencies", () => {
  assert.ok(manifest.dependencies?.["html-to-text"]);
  assert.ok(manifest.dependencies?.["ipaddr.js"]);
  assert.ok(existsSync(join(root, "packages/pi-tai/src/web/register.ts")));
  const childRuntime = readFileSync(join(root, "packages/pi-tai/subagent.ts"), "utf8");
  assert.match(childRuntime, /registerWebTools\(pi\)/);
  assert.ok(childRuntime.indexOf("registerWebTools(pi)") < childRuntime.indexOf("registerSubagents(pi"));
});

function readFileOrDirectoryExists(path: string): boolean {
  return existsSync(path);
}

function walkSource(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return walkSource(path);
    return entry.name.endsWith(".ts") ? [path] : [];
  });
}
