// @generated by pi-tai-runtime-protocol. Do not edit.

// This file has been generated by Specta. Do not edit this file manually.
export type AcceptedResult = {
	accepted: boolean,
};

export type CommandFrameKind = "command";

export type EmptyParams = Record<string, never>;

export type EmptyResult = Record<string, never>;

export type EventFrameKind = "event";

export type InterruptionData = {
	reason: string,
};

export type ModelInfo = {
	provider: string,
	model: string,
};

export type ProtocolRange = {
	minVersion: number,
	maxVersion: number,
};

export type QueueData = {
	steeringCount: number,
	followUpCount: number,
};

export type ResponseFrameKind = "response";

export type RuntimeCapabilities = {
	methods: string[],
	tools: string[],
	commands: string[],
	extensionErrors: string[],
};

export type RuntimeCommand = {
	protocolVersion: number,
	kind: CommandFrameKind,
	id: string,
	method: string,
	params: unknown,
};

export type RuntimeEvent = RuntimeEvent_Serialize | RuntimeEvent_Deserialize;

export type RuntimeEvent_Deserialize = {
	protocolVersion: number,
	kind: EventFrameKind,
	workerSequence: number,
	runtimeGeneration: number,
	event: string,
	commandId: string | null,
	sessionId: string | null,
	turnId: string | null,
	data: unknown,
};

export type RuntimeEvent_Serialize = {
	protocolVersion: number,
	kind: EventFrameKind,
	workerSequence: number,
	runtimeGeneration: number,
	event: string,
	commandId?: string | null,
	sessionId?: string | null,
	turnId?: string | null,
	data: unknown,
};

export type RuntimeInitializeParams = RuntimeInitializeParams_Serialize | RuntimeInitializeParams_Deserialize;

export type RuntimeInitializeParams_Deserialize = {
	protocol: ProtocolRange,
	workerId: string,
	runtimeGeneration: number,
};

export type RuntimeInitializeParams_Serialize = {
	protocol: ProtocolRange,
	workerId: string,
	runtimeGeneration: number,
};

export type RuntimeInitializeResult = RuntimeInitializeResult_Serialize | RuntimeInitializeResult_Deserialize;

export type RuntimeInitializeResult_Deserialize = {
	protocolVersion: number,
	workerId: string,
	runtimeGeneration: number,
	capabilities: RuntimeCapabilities,
};

export type RuntimeInitializeResult_Serialize = {
	protocolVersion: number,
	workerId: string,
	runtimeGeneration: number,
	capabilities: RuntimeCapabilities,
};

export type RuntimeProtocolError = RuntimeProtocolError_Serialize | RuntimeProtocolError_Deserialize;

export type RuntimeProtocolError_Deserialize = {
	code: string,
	message: string,
	retryable: boolean,
	details: unknown | null,
};

export type RuntimeProtocolError_Serialize = {
	code: string,
	message: string,
	retryable: boolean,
	details?: unknown | null,
};

export type RuntimeResponse = RuntimeResponse_Serialize | RuntimeResponse_Deserialize;

export type RuntimeResponse_Deserialize = {
	protocolVersion: number,
	kind: ResponseFrameKind,
	id: string,
	ok: boolean,
	result: unknown | null,
	error: RuntimeProtocolError_Deserialize | null,
};

export type RuntimeResponse_Serialize = {
	protocolVersion: number,
	kind: ResponseFrameKind,
	id: string,
	ok: boolean,
	result?: unknown | null,
	error?: RuntimeProtocolError_Serialize | null,
};

export type SessionCancelParams = {
	turnId: string,
};

export type SessionCreateParams = {
	cwd: string,
	agentDir: string,
	sessionDir: string,
	faux?: boolean,
};

export type SessionInfo = {
	sessionId: string,
	sessionFile: string,
	cwd: string,
};

export type SessionOpenParams = {
	sessionFile: string,
	agentDir: string,
	sessionDir: string,
	faux?: boolean,
};

export type SessionPromptParams = {
	turnId: string,
	text: string,
};

export type SessionSetModelParams = {
	provider: string,
	model: string,
};

export type SessionSetThinkingParams = {
	level: ThinkingLevel,
};

export type SessionTextParams = {
	text: string,
};

export type SessionTitleData = SessionTitleData_Serialize | SessionTitleData_Deserialize;

export type SessionTitleData_Deserialize = {
	title: string | null,
};

export type SessionTitleData_Serialize = {
	title?: string | null,
};

export type TextDeltaData = {
	delta: string,
};

export type ThinkingInfo = {
	level: ThinkingLevel,
};

export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

export type ToolLifecycleData = ToolLifecycleData_Serialize | ToolLifecycleData_Deserialize;

export type ToolLifecycleData_Deserialize = {
	toolCallId: string,
	toolName: string,
	isError: boolean | null,
};

export type ToolLifecycleData_Serialize = {
	toolCallId: string,
	toolName: string,
	isError?: boolean | null,
};
