// @generated by pi-tai-runtime-protocol. Do not edit.

// This file has been generated by Specta. Do not edit this file manually.
export type AcceptedResult = {
	accepted: boolean,
};

export type CommandFrameKind = "command";

export type CompactionConfig = {
	enabled: boolean,
	thresholdPercent: number,
};

export type ConfigLayer = "default" | "machine" | "user" | "project";

export type ConfigProvenance = ConfigProvenance_Serialize | ConfigProvenance_Deserialize;

export type ConfigProvenance_Deserialize = { [key in string]: FieldOrigin_Deserialize };

export type ConfigProvenance_Serialize = { [key in string]: FieldOrigin_Serialize };

export type ConfigScope = "machine" | "project" | "session";

export type EmptyParams = Record<string, never>;

export type EmptyResult = Record<string, never>;

export type EventFrameKind = "event";

export type FieldDescriptor = {
	scope: ConfigScope,
	privileged: boolean,
};

export type FieldOrigin = FieldOrigin_Serialize | FieldOrigin_Deserialize;

export type FieldOrigin_Deserialize = {
	layer: ConfigLayer,
	path?: string | null,
	digest?: string | null,
};

export type FieldOrigin_Serialize = {
	layer: ConfigLayer,
	path?: string | null,
	digest?: string | null,
};

export type HostServiceResponseParams = HostServiceResponseParams_Serialize | HostServiceResponseParams_Deserialize;

export type HostServiceResponseParams_Deserialize = {
	requestId: string,
	ok: boolean,
	result: unknown | null,
	error: RuntimeProtocolError_Deserialize | null,
};

export type HostServiceResponseParams_Serialize = {
	requestId: string,
	ok: boolean,
	result?: unknown | null,
	error?: RuntimeProtocolError_Serialize | null,
};

export type InterruptionData = {
	reason: string,
};

export type ModelInfo = {
	provider: string,
	model: string,
};

export type ModelProfile = {
	name: string,
	provider: string,
	model: string,
	effort: ThinkingEffort,
};

export type ProtocolRange = {
	minVersion: number,
	maxVersion: number,
};

export type QueueData = {
	steeringCount: number,
	followUpCount: number,
};

export type ResponseFrameKind = "response";

export type RuntimeCapabilities = {
	methods: string[],
	tools: string[],
	commands: string[],
	extensionErrors: string[],
};

export type RuntimeCommand = {
	protocolVersion: number,
	kind: CommandFrameKind,
	id: string,
	method: string,
	params: unknown,
};

export type RuntimeEvent = RuntimeEvent_Serialize | RuntimeEvent_Deserialize;

export type RuntimeEvent_Deserialize = {
	protocolVersion: number,
	kind: EventFrameKind,
	workerSequence: number,
	runtimeGeneration: number,
	event: string,
	commandId: string | null,
	sessionId: string | null,
	turnId: string | null,
	data: unknown,
};

export type RuntimeEvent_Serialize = {
	protocolVersion: number,
	kind: EventFrameKind,
	workerSequence: number,
	runtimeGeneration: number,
	event: string,
	commandId?: string | null,
	sessionId?: string | null,
	turnId?: string | null,
	data: unknown,
};

export type RuntimeInitializeParams = RuntimeInitializeParams_Serialize | RuntimeInitializeParams_Deserialize;

export type RuntimeInitializeParams_Deserialize = {
	protocol: ProtocolRange,
	workerId: string,
	runtimeGeneration: number,
};

export type RuntimeInitializeParams_Serialize = {
	protocol: ProtocolRange,
	workerId: string,
	runtimeGeneration: number,
};

export type RuntimeInitializeResult = RuntimeInitializeResult_Serialize | RuntimeInitializeResult_Deserialize;

export type RuntimeInitializeResult_Deserialize = {
	protocolVersion: number,
	workerId: string,
	runtimeGeneration: number,
	capabilities: RuntimeCapabilities,
};

export type RuntimeInitializeResult_Serialize = {
	protocolVersion: number,
	workerId: string,
	runtimeGeneration: number,
	capabilities: RuntimeCapabilities,
};

export type RuntimeProtocolError = RuntimeProtocolError_Serialize | RuntimeProtocolError_Deserialize;

export type RuntimeProtocolError_Deserialize = {
	code: string,
	message: string,
	retryable: boolean,
	details: unknown | null,
};

export type RuntimeProtocolError_Serialize = {
	code: string,
	message: string,
	retryable: boolean,
	details?: unknown | null,
};

export type RuntimeResponse = RuntimeResponse_Serialize | RuntimeResponse_Deserialize;

export type RuntimeResponse_Deserialize = {
	protocolVersion: number,
	kind: ResponseFrameKind,
	id: string,
	ok: boolean,
	result: unknown | null,
	error: RuntimeProtocolError_Deserialize | null,
};

export type RuntimeResponse_Serialize = {
	protocolVersion: number,
	kind: ResponseFrameKind,
	id: string,
	ok: boolean,
	result?: unknown | null,
	error?: RuntimeProtocolError_Serialize | null,
};

export type SessionCancelParams = {
	turnId: string,
};

export type SessionCreateParams = SessionCreateParams_Serialize | SessionCreateParams_Deserialize;

export type SessionCreateParams_Deserialize = {
	cwd: string,
	rootSessionId: string | null,
	runtimeGeneration?: number | null,
	agentDir: string,
	sessionDir: string,
	sessionPolicy: SessionPolicy,
	policyProvenance: ConfigProvenance_Deserialize,
	faux?: boolean,
};

export type SessionCreateParams_Serialize = {
	cwd: string,
	rootSessionId?: string | null,
	runtimeGeneration?: number | null,
	agentDir: string,
	sessionDir: string,
	sessionPolicy: SessionPolicy,
	policyProvenance: ConfigProvenance_Serialize,
	faux: boolean,
};

export type SessionInfo = {
	sessionId: string,
	sessionFile: string,
	cwd: string,
};

export type SessionOpenParams = SessionOpenParams_Serialize | SessionOpenParams_Deserialize;

export type SessionOpenParams_Deserialize = {
	sessionFile: string,
	rootSessionId: string | null,
	runtimeGeneration?: number | null,
	agentDir: string,
	sessionDir: string,
	sessionPolicy: SessionPolicy,
	policyProvenance: ConfigProvenance_Deserialize,
	faux?: boolean,
};

export type SessionOpenParams_Serialize = {
	sessionFile: string,
	rootSessionId?: string | null,
	runtimeGeneration?: number | null,
	agentDir: string,
	sessionDir: string,
	sessionPolicy: SessionPolicy,
	policyProvenance: ConfigProvenance_Serialize,
	faux: boolean,
};

export type SessionPolicy = {
	compaction: CompactionConfig,
	modelProfiles: ModelProfile[],
};

export type SessionPromptParams = {
	turnId: string,
	text: string,
};

export type SessionRelocateWorkspaceParams = {
	backend: WorkspaceBackend,
	name: string,
};

export type SessionSetModelParams = {
	provider: string,
	model: string,
};

export type SessionSetThinkingParams = {
	level: ThinkingLevel,
};

export type SessionTextParams = {
	text: string,
};

export type SessionTitleData = SessionTitleData_Serialize | SessionTitleData_Deserialize;

export type SessionTitleData_Deserialize = {
	title: string | null,
};

export type SessionTitleData_Serialize = {
	title?: string | null,
};

export type TextDeltaData = {
	delta: string,
};

export type ThinkingEffort = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

export type ThinkingInfo = {
	level: ThinkingLevel,
};

export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

export type ToolLifecycleData = ToolLifecycleData_Serialize | ToolLifecycleData_Deserialize;

export type ToolLifecycleData_Deserialize = {
	toolCallId: string,
	toolName: string,
	isError: boolean | null,
};

export type ToolLifecycleData_Serialize = {
	toolCallId: string,
	toolName: string,
	isError?: boolean | null,
};

export type WorkspaceBackend = "jj" | "git";
