import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { FileReviewStore, ReviewService } from "../../packages/pi-tai/src/concurrency/reviews.ts";
const A = "a".repeat(32), B = "b".repeat(32), HASH = "0".repeat(64);
async function setup(root: string) { const service = new ReviewService(new FileReviewStore(root)); const bundle = await service.prepare({ workspaceId: "workspace-1", reportVersion: 1, taskSnapshot: { snapshotId: "snapshot-1", taskId: "task-1", digest: HASH, path: "/tmp/task.md", bytes: 1, createdAt: "now" }, rootChangeId: A, workspaceHeadChangeId: "c".repeat(32), contentTipChangeId: B, orderedChangeIds: [A, B], normalizedPatchHash: HASH, conflictPaths: [], evidenceDigest: HASH }); return { service, bundle }; }
test("review approval blocks p0/p1 and requires p2 dispositions", async () => { const root = await mkdtemp(join(tmpdir(), "pi-tai-reviews-")); try { const { service, bundle } = await setup(root); await service.submit(bundle.bundleId, { reviewerContextId: "reviewer-1", cycle: 0, summary: "Needs work", findings: [{ findingId: "finding-1", severity: "p1", relation: "introduced", summary: "Broken", evidence: "test fails", changeIds: [A], paths: ["a.ts"], focusedReviewable: true }], validation: [] }); await assert.rejects(service.approve(bundle.bundleId, { approvedByContextId: "thinker-1", dispositions: [] }), /must be fixed/); } finally { await rm(root, { recursive: true, force: true }); } });
test("review service mints immutable approval for nonblocking findings", async () => { const root = await mkdtemp(join(tmpdir(), "pi-tai-reviews-")); try { const { service, bundle } = await setup(root); await service.submit(bundle.bundleId, { reviewerContextId: "reviewer-1", cycle: 0, summary: "Acceptable", findings: [{ findingId: "finding-2", severity: "p2", relation: "introduced", summary: "Improve later", evidence: "bounded", changeIds: [B], paths: [], focusedReviewable: false }], validation: ["tests pass"] }); const receipt = await service.approve(bundle.bundleId, { approvedByContextId: "thinker-1", dispositions: [{ findingId: "finding-2", disposition: "deferred", rationale: "outside acceptance" }] }); assert.equal((await service.requireApproval(bundle.bundleId)).receiptDigest, receipt.receiptDigest); } finally { await rm(root, { recursive: true, force: true }); } });
