import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { changeDescription, workspaceName } from "../../packages/pi-tai/src/jj/domain.ts";
import { IsolatedJjRuntime } from "../../packages/pi-tai/src/jj/isolated-runtime.ts";
import { RealJjFixture } from "../support/real-jj-fixture.ts";

test("nonempty tracked workspace requires task-bound review before integration and verification", async () => {
  const fixture = await RealJjFixture.create("pi-tai-m4-integration-"); let interruptIntegration = false;
  try {
    await fixture.seed({ changes: [{ description: "base", files: { "base.txt": "base\n" } }] }); const runtime = new IsolatedJjRuntime({ stateRoot: join(fixture.root, "state"), executor: fixture.executor, failpoint: (operation, boundary) => { if (interruptIntegration && operation === "integrate_workspace" && boundary === "range_inserted") { interruptIntegration = false; throw new Error("injected integration interruption"); } } }); const source = await runtime.shared.openSource(fixture.repoPath); assert.equal((await runtime.shared.operations.ensureWip(source)).kind, "completed"); await writeFile(join(fixture.repoPath, "source.txt"), "preserve\n"); const sourceId = await fixture.currentChangeId(fixture.repoPath); const sourcePatch = await fixture.run(fixture.repoPath, ["diff", "--revision", "@", "--git"]);
    const userContent = "Implement reviewed feature"; const task = await runtime.tasks.createRoot({ rootSessionId: "root-1", orchestratorContextId: "orchestrator-1", objective: userContent, acceptanceCriteria: ["feature exists"], userRequest: { messageId: "user-1", content: userContent, contentHash: createHash("sha256").update(userContent).digest("hex"), observedAt: "now" } }); await runtime.tasks.appendPlan(task.taskId, { authorContextId: "orchestrator-1", authorRole: "orchestrator", authorityMessageId: "user-1", markdown: "Implement and independently review the feature", rationale: "Approved design" }); const approvalContent = "I approve this plan"; await runtime.tasks.approvePlan(task.taskId, { orchestratorContextId: "orchestrator-1", evidence: { messageId: "user-approval-1", content: approvalContent, contentHash: createHash("sha256").update(approvalContent).digest("hex"), observedAt: "approved" } }); const implementationTask = await runtime.tasks.assign(task.taskId, { ownerRole: "implementation-lead", creatorContextId: "orchestrator-1", objective: "Add feature" }); await runtime.tasks.bind(implementationTask.taskId, "implementation-lead-1");
    const created = await runtime.operations.createWorkspace(source, { name: workspaceName("reviewed"), ownerContextId: "implementation-lead-1", rootSessionId: "root-1" }); assert.equal(created.kind, "completed"); if (created.kind !== "completed") return; await writeFile(join(created.receipt.path, "feature.txt"), "feature\n"); const checkpoint = await runtime.operations.checkpointWorkspace(created.receipt.lease, { description: changeDescription("feat: add reviewed feature") }); assert.equal(checkpoint.kind, "completed"); if (checkpoint.kind !== "completed") return; await runtime.operations.releaseWriter(checkpoint.receipt.lease); assert.equal((await runtime.operations.prepareWorkspaceReport(created.receipt.workspaceId)).kind, "completed");
    await runtime.reviewCoordinator.acknowledge(created.receipt.workspaceId, { implementationEventId: "event-1", taskId: implementationTask.taskId }); const reviewerTask = await runtime.tasks.assign(implementationTask.taskId, { ownerRole: "reviewer", creatorContextId: "orchestrator-1", objective: "Review exact range" }); await runtime.tasks.bind(reviewerTask.taskId, "reviewer-1"); const bundle = await runtime.reviewCoordinator.prepareReview(created.receipt.workspaceId); await runtime.reviewCoordinator.submitReview(created.receipt.workspaceId, { reviewerContextId: "reviewer-1", summary: "Approved", findings: [], validation: ["feature matches goal"] });
    const redirected = "Preserve the feature but validate the redirected intent"; await runtime.tasks.recordDirection(task.taskId, { orchestratorContextId: "orchestrator-1", summary: "Validate redirected intent", evidence: { messageId: "user-2", content: redirected, contentHash: createHash("sha256").update(redirected).digest("hex"), observedAt: "later" } }); await assert.rejects(runtime.reviewCoordinator.approve(created.receipt.workspaceId, { orchestratorContextId: "orchestrator-1", dispositions: [] }), /task snapshot is stale/); assert.equal((await runtime.workspaces.get(created.receipt.workspaceId))?.phase, "acknowledged"); await runtime.tasks.appendPlan(task.taskId, { authorContextId: "orchestrator-1", authorRole: "orchestrator", authorityMessageId: "user-2", markdown: "Implement with redirected validation", rationale: "Applied redirected intent" }); const redirectedApproval = "Approved, go ahead"; await runtime.tasks.approvePlan(task.taskId, { orchestratorContextId: "orchestrator-1", evidence: { messageId: "user-approval-2", content: redirectedApproval, contentHash: createHash("sha256").update(redirectedApproval).digest("hex"), observedAt: "reapproved" } }); const redirectedBundle = await runtime.reviewCoordinator.prepareReview(created.receipt.workspaceId); assert.notEqual(redirectedBundle.taskSnapshot.digest, bundle.taskSnapshot.digest); await runtime.reviewCoordinator.submitReview(created.receipt.workspaceId, { reviewerContextId: "reviewer-2", summary: "Redirected intent approved", findings: [], validation: ["feature matches redirected goal"] }); await runtime.reviewCoordinator.approve(created.receipt.workspaceId, { orchestratorContextId: "orchestrator-1", dispositions: [] });
    const postApprovalDirection = "Also preserve compatibility evidence"; await runtime.tasks.recordDirection(task.taskId, { orchestratorContextId: "orchestrator-1", summary: "Preserve compatibility evidence", evidence: { messageId: "user-3", content: postApprovalDirection, contentHash: createHash("sha256").update(postApprovalDirection).digest("hex"), observedAt: "latest" } }); await assert.rejects(runtime.integration.integrate(created.receipt.workspaceId), /review approval is stale/); assert.equal((await runtime.workspaces.get(created.receipt.workspaceId))?.phase, "acknowledged"); await runtime.tasks.appendPlan(task.taskId, { authorContextId: "orchestrator-1", authorRole: "orchestrator", authorityMessageId: "user-3", markdown: "Implement with compatibility evidence", rationale: "Applied latest intent" }); const latestApproval = "Go ahead and implement"; await runtime.tasks.approvePlan(task.taskId, { orchestratorContextId: "orchestrator-1", evidence: { messageId: "user-approval-3", content: latestApproval, contentHash: createHash("sha256").update(latestApproval).digest("hex"), observedAt: "latest-approved" } }); await runtime.reviewCoordinator.prepareReview(created.receipt.workspaceId); await runtime.reviewCoordinator.submitReview(created.receipt.workspaceId, { reviewerContextId: "reviewer-3", summary: "Latest intent approved", findings: [], validation: ["feature preserves compatibility evidence"] }); await runtime.reviewCoordinator.approve(created.receipt.workspaceId, { orchestratorContextId: "orchestrator-1", dispositions: [] });
    interruptIntegration = true; await assert.rejects(runtime.integration.integrate(created.receipt.workspaceId), /injected integration interruption/); const interrupted = await runtime.workspaces.get(created.receipt.workspaceId); assert.equal(interrupted?.phase, "integrating"); const integrated = await runtime.integration.resume(created.receipt.workspaceId); assert.equal(integrated.conflicted, false); assert.equal(await fixture.currentChangeId(fixture.repoPath), sourceId); assert.equal(await fixture.run(fixture.repoPath, ["diff", "--revision", "@", "--git"]), sourcePatch); assert.equal(bundle.taskSnapshot.taskId, implementationTask.taskId);
    const verification = await runtime.closure.verify(created.receipt.workspaceId, ["feature acceptance passed"]); await runtime.closure.close(created.receipt.workspaceId); assert.match(verification.verificationId, /^verification-/); assert.equal((await runtime.workspaces.get(created.receipt.workspaceId))?.phase, "closed");
  } catch (error) { const retained = await fixture.retainOnFailure("M4 integration"); if (error instanceof Error) error.message += `\nRetained fixture: ${retained.path}`; throw error; } finally { await fixture.dispose(); }
});
