import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { changeDescription, workspaceName } from "../../packages/pi-tai/src/jj/domain.ts";
import { IsolatedJjRuntime } from "../../packages/pi-tai/src/jj/isolated-runtime.ts";
import { RealJjFixture } from "../support/real-jj-fixture.ts";

test("nonempty tracked workspace requires task-bound review before integration and verification", async () => {
  const fixture = await RealJjFixture.create("pi-tai-m4-integration-"); let interruptIntegration = false;
  try {
    await fixture.seed({ changes: [{ description: "base", files: { "base.txt": "base\n" } }] }); const runtime = new IsolatedJjRuntime({ stateRoot: join(fixture.root, "state"), executor: fixture.executor, failpoint: (operation, boundary) => { if (interruptIntegration && operation === "integrate_workspace" && boundary === "range_inserted") { interruptIntegration = false; throw new Error("injected integration interruption"); } } }); const source = await runtime.shared.openSource(fixture.repoPath); assert.equal((await runtime.shared.operations.ensureWip(source)).kind, "completed"); await writeFile(join(fixture.repoPath, "source.txt"), "preserve\n"); const sourceId = await fixture.currentChangeId(fixture.repoPath); const sourcePatch = await fixture.run(fixture.repoPath, ["diff", "--revision", "@", "--git"]);
    const userContent = "Implement reviewed feature"; const task = await runtime.tasks.createRoot({ rootSessionId: "root-1", thinkerContextId: "thinker-1", objective: userContent, acceptanceCriteria: ["feature exists"], userRequest: { messageId: "user-1", content: userContent, contentHash: createHash("sha256").update(userContent).digest("hex"), observedAt: "now" } }); const implementationTask = await runtime.tasks.assign(task.taskId, { ownerRole: "worker", creatorContextId: "thinker-1", objective: "Add feature" }); await runtime.tasks.bind(implementationTask.taskId, "worker-1");
    const created = await runtime.operations.createWorkspace(source, { name: workspaceName("reviewed"), ownerContextId: "worker-1", rootSessionId: "root-1" }); assert.equal(created.kind, "completed"); if (created.kind !== "completed") return; await writeFile(join(created.receipt.path, "feature.txt"), "feature\n"); const checkpoint = await runtime.operations.checkpointWorkspace(created.receipt.lease, { description: changeDescription("feat: add reviewed feature") }); assert.equal(checkpoint.kind, "completed"); if (checkpoint.kind !== "completed") return; await runtime.operations.releaseWriter(checkpoint.receipt.lease); assert.equal((await runtime.operations.prepareWorkspaceReport(created.receipt.workspaceId)).kind, "completed");
    await runtime.reviewCoordinator.acknowledge(created.receipt.workspaceId, { implementationEventId: "event-1", taskId: implementationTask.taskId }); const bundle = await runtime.reviewCoordinator.prepareReview(created.receipt.workspaceId); await runtime.reviewCoordinator.submitReview(created.receipt.workspaceId, { reviewerContextId: "reviewer-1", summary: "Approved", findings: [], validation: ["feature matches goal"] });
    const redirected = "Preserve the feature but validate the redirected intent"; await runtime.tasks.recordDirection(task.taskId, { thinkerContextId: "thinker-1", summary: "Validate redirected intent", evidence: { messageId: "user-2", content: redirected, contentHash: createHash("sha256").update(redirected).digest("hex"), observedAt: "later" } }); await assert.rejects(runtime.reviewCoordinator.approve(created.receipt.workspaceId, { thinkerContextId: "thinker-1", dispositions: [] }), /task snapshot is stale/); assert.equal((await runtime.workspaces.get(created.receipt.workspaceId))?.phase, "acknowledged"); const redirectedBundle = await runtime.reviewCoordinator.prepareReview(created.receipt.workspaceId); assert.notEqual(redirectedBundle.taskSnapshot.digest, bundle.taskSnapshot.digest); await runtime.reviewCoordinator.submitReview(created.receipt.workspaceId, { reviewerContextId: "reviewer-2", summary: "Redirected intent approved", findings: [], validation: ["feature matches redirected goal"] }); await runtime.reviewCoordinator.approve(created.receipt.workspaceId, { thinkerContextId: "thinker-1", dispositions: [] });
    interruptIntegration = true; await assert.rejects(runtime.integration.integrate(created.receipt.workspaceId), /injected integration interruption/); const interrupted = await runtime.workspaces.get(created.receipt.workspaceId); assert.equal(interrupted?.phase, "integrating"); const integrated = await runtime.integration.resume(created.receipt.workspaceId); assert.equal(integrated.conflicted, false); assert.equal(await fixture.currentChangeId(fixture.repoPath), sourceId); assert.equal(await fixture.run(fixture.repoPath, ["diff", "--revision", "@", "--git"]), sourcePatch); assert.equal(bundle.taskSnapshot.taskId, implementationTask.taskId);
    const verification = await runtime.closure.verify(created.receipt.workspaceId, ["feature acceptance passed"]); await runtime.closure.close(created.receipt.workspaceId); assert.match(verification.verificationId, /^verification-/); assert.equal((await runtime.workspaces.get(created.receipt.workspaceId))?.phase, "closed");
  } catch (error) { const retained = await fixture.retainOnFailure("M4 integration"); if (error instanceof Error) error.message += `\nRetained fixture: ${retained.path}`; throw error; } finally { await fixture.dispose(); }
});
